### ISSUE TITLE
Изменился РУИД объекта

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#10]
14:42:16
Поиск объекта по потенциальному ключу:
SELECT c.id FROM gd_contact c JOIN gd_company co ON co.contactkey = c.id   LEFT JOIN gd_companycode cp ON cp.companykey = c.id WHERE UPPER(c.name)=UPPER(:name) AND cp.taxid IS NOT DISTINCT FROM :taxid 
NAME: 1
TAXID: <УНП не указан>
14:42:16  Объект найден по потенциальному ключу: 1 (Организация)
14:42:16  Изменяется объект: 1, 147002588_279245339, gd_contact
[Предупреждение] 14:42:16  Отсутствует в файле: "GD_CONTACT"."USR$ETTN_GLN"
14:42:16  Изменен объект: 1 (Организация)
[Предупреждение] 14:42:16  Изменился РУИД объекта 147002587_357866314 -> 147002588_279245339

в разных ПИ есть компания 1 с разными РУИДами.

**Comment by alexandra-gsoftware** [comment]
А что это за ПИ? На эталоне нет ни 147002587_357866314, ни 147002588_279245339

**Comment by gsbelarus** [comment]
санаторий
