### ISSUE TITLE
Расчетный листок vs. льготы, вычеты

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin-apps#11]
Выяснился один неприятный момент, касающийся расчетного листка.
Поясню.  Есть такие вещи в расчетном, как льготы, вычеты,
которые подтягиваются в расчетный из USR$WG_CHREGADDINFO (Доп. инф по начислениям)
Часть данных туда попадает из докумнета (прописано на методе) "Наоблагаемые суммы", "состав семьи", а часть непосредственно в момент итогового расчета. Все бы ничего, но нередко бывают такие случаи, когда приносится справка позже и она разносится задним числом, чтобы потом пересчитать макросом налоги. В USR$WG_CHREGADDINFO на методе добавляются записи. В итоге получаем ситуацию, когда, например, в феврале мы построили расчетыный  - там одни льготы , вычеты, а когда разнесли задним числом справку и снова построили расчетный, то "лезут" дополнительные  льготы, которые по факту никакого отношения не имеют к февральскому расчету. 
Возможно следует, добавить какое -то поле бул., кототрое при первом заполнении заполняется, а при пересчете итогового зануляется? и при построениив расчтеного позиции с таким признаком не брать.

Повторюсь, это касается ТОЛЬКО расчетного листка(отчета). Подоходный считается корректно.

**Comment by alexandra-gsoftware** [comment]
макрос пересчета начислений немного косячный. Он на отдельной транзакции очищает начисления по табелю, считает заново нужное начисление, закидывает ручным вводом разницу между тем, что сейчас посчитано и тем, что было, и откатывает транзакцию. А при расчете подоходного идет запись в дополнительные таблицы (т.е. с откатыванием транзакции проблема)... там надо очень хорошо подумать, как это грамотно переделать.

**Comment by MikhailVAS** [comment]
'#include PFD_FINDORADDGOOD
'#include PFD_FINDGOODWITHOUTADDING
'#include PFD_SYNCDEPOT
option explicit
function pfd_ExportFromDepotInServer(DepKey, ID, DocType, EndDate, gdcO)
  if Assigned(gdcO) then
    if gdcO.FieldByName("USR$PFD_DELIVERED").AsInteger = 1 then
      if Application.MessageBox("Íàêëàäíàÿ óæå ýêñïîðòèðîâàíà!
Ýêñïîðòèðîâàòü åùå ðàç?", "Âíèìàíèå", vbSystemModal + vbYesNo) = vbNo then
        exit function
      end if
    end if
    if DocType = gdcBaseManager.GetIDByRUIDString("147013048_109092844")
then
     ' if gdcO.FieldByName("BillDelivered").AsInteger = 1 then
'          call Application.MessageBox("Íàêëàäíàÿ, ïðèâÿçàííàÿ ê äîê-òó
ïåðåîöåíêè, óæå ýêñïîðòèðîâàíà!", "Âíèìàíèå", vbSystemModal + mb_IconError)
'        exit function
'      end if
    end if
  end if

  dim Creator, Transaction, Database, OurTransaction
  set Creator = new TCreator
  dim qParams, Params
  'Ïóòü ê êàññîâîìó ñåðâåðó
  set qParams = Creator.GetObject(nil, "TIBSQL", "")
  qParams.Transaction = gdcBaseManager.ReadTransaction
  qParams.SQL.Text = _
    " SELECT USR$DEPOTKEY, USR$PATH " & _
    " FROM USR$SERVERDEP " & _
    " WHERE USR$DEPOTKEY = :depkey AND COALESCE(USR$DISABLED, 0) = 0 "
  qParams.ParamByName("depkey").AsInteger = DepKey
  qParams.ExecQuery

  set Transaction = Creator.GetObject(nil, "TIBTransaction", "")
  Transaction.Params.Add("nowait")
  set Database = Creator.GetObject(nil, "TIBDatabase", "")
  if qParams.EoF then
    if not pf_Silent then
      call Application.MessageBox("Âûáðàííîå ïîäðàçäåëåíèå íå ñâÿçàíî ñ
êàññîâûì ñåðâåðîì!", "Âíèìàíèå", vbSystemModal + mb_IconError)
    end if
    exit function
  end if

  'Ïóòü ê áàçå
  Database.DatabaseName = qParams.FieldByName("USR$PATH").AsString
  Database.DefaultTransaction = Transaction
  Database.Params.Add("user_name=SYSDBA")
  Database.Params.Add("password=masterkey")
  Database.Params.Add("lc_ctype=win1251")
  Database.LoginPrompt = False
  if not Database.Connected then
    ON ERROR RESUME NEXT
      Database.Open
      if Err.Description <> "" then
        if not pf_Silent then
          call Application.MessageBox(Err.Description, "Âíèìàíèå!",
vbSystemModal + vbCritical)
        end if
        Exit Function
      end if
    ON ERROR GOTO 0
  end if

  dim SelectPart, FromPart, GroupPart, FeatureNamesArr, AllPart
  AllPart = pfd_ExportFromDepotInServer_GetClauses(Creator, (DocType = 0))
  SelectPart = AllPart(0)
  FromPart = AllPart(1)
  GroupPart = AllPart(2)
  FeatureNamesArr = Split(AllPart(3), ";")

  ' Íàêëàäíûå
  dim sqlGoodBill,  isOurCompany, qComp
  isOurCompany = false

  set OurTransaction = Creator.GetObject(nil, "TIBTransaction", "")
  OurTransaction.DefaultDatabase = gdcBaseManager.Database

  dim qIsExp

  set sqlGoodBill = Creator.GetObject(nil, "TIBSQL", "")
  sqlGoodBill.Transaction = gdcBaseManager.ReadTransaction

  set qIsExp = Creator.GetObject(nil, "TIBSQL", "")
  qIsExp.Transaction = OurTransaction
  ' Åñëè Íàêëàäíàÿ íà ïîëó÷åíèå.
  if DocType = gdcBaseManager.GetIDByRUIDString("147010993_109092844") then
    ''' Îïåðåäÿåì ïîñòàâùèêà

    qIsExp.SQL.Text = _
      " UPDATE USR$INV_ADDWBILLLINE " & _
      " SET USR$ISEXPORT = 1 " & _
      " WHERE QUANTITY = :q AND MASTERKEY = :dockey AND DOCUMENTKEY IN  " &
_
      "   (SELECT l.DOCUMENTKEY " & _
      "    FROM USR$INV_ADDWBILLLINE l " & _
      "    LEFT JOIN INV_CARD c ON c.ID = l.FROMCARDKEY " & _
      "    LEFT JOIN GD_GOOD g ON g.ID = c.GOODKEY " & _
      "    WHERE l.MASTERKEY = :dockey AND
COALESCE(c.USR$INV_COSTRETAILNCU, 0) = :cost  " & _
      "      AND c.GOODKEY = :goodkey AND COALESCE(l.QUANTITY, 0) = :q )"

    set qComp = Creator.GetObject(nil, "TIBSQL", "")
    qComp.Transaction = gdcBaseManager.ReadTransaction
    qComp.SQL.Text = _
      "select * from gd_company com where com.HEADCOMPANY = :headid and
com.CONTACTKEY = :conkey"
    qComp.ParamByName("headid").AsInteger =
gdcBaseManager.GetIDByRUIDString("151768829_2115439882")     '''' ID
ãëàâíîé îðãàíèçàöèè ÌÕÏ
    qComp.ParamByName("conkey").AsInteger =
gdcO.FieldByname("USR$CONTACTKEY").AsInteger
    qComp.ExecQuery
    ''''
    if not qComp.EoF then
      isOurCompany = true
    end if

    '''
    sqlGoodBill.SQL.Text = _
    "SELECT " & _
    "  bill.USR$DEPTKEY AS CONID, " & _
    "  g.ID, " & _
    "  g.ALIAS, " & _
    "  g.NAME, " & _
    "  g.USR$PF_ISWEIGHT, " & _
    "  g.BARCODE AS BARCODE, " & _
    "  g.USR$PF_ISFRAC, " & _
    "  c.USR$INV_COSTRETAILNCU, " & _
    "    iif(bline.USR$ISDISC=1,(C.USR$INV_COSTBUYNCU +
C.USR$INV_BUYNDSNCU),0) AS COST, " & _
    "  v.NAME AS ValueName, " & _
    "  bline.QUANTITY, bline.USR$ISSPEND, bline.USR$ISEXPORT " & _
    SelectPart & _
    "    FROM USR$INV_ADDWBILL bill " & _
    "  LEFT JOIN GD_DOCUMENT d ON bill.DOCUMENTKEY = d.ID " & _
    "  LEFT JOIN USR$INV_ADDWBILLLINE bline ON bill.DOCUMENTKEY =
bline.MASTERKEY " & _
    "  LEFT JOIN INV_CARD c ON c.ID = bline.FROMCARDKEY " & _
    "  LEFT JOIN GD_GOOD g ON g.ID = c.GOODKEY " & _
    "  LEFT JOIN GD_VALUE v ON g.VALUEKEY = v.ID " & _
    FromPart & _
    "WHERE bill.DOCUMENTKEY = :dockey "

  ' Åñëè Âûäà÷à â òîðãîâûå ïîäðàçäåëåíèÿ
  elseif DocType = gdcBaseManager.GetIDByRUIDString("147005934_63934951")
then
    sqlGoodBill.SQL.Text = _
      "SELECT " & _
      "  bill.USR$CONTACTKEY AS CONID, " & _
      "  g.ID, " & _
      "  g.ALIAS, " & _
      "  g.NAME, " & _
      "  g.USR$PF_ISWEIGHT, " & _
      "  g.BARCODE AS BARCODE, " & _
      "  g.USR$PF_ISFRAC, " & _
      "  c.USR$INV_COSTRETAILNCU, " & _
      "  0 as Cost, " & _
      "  v.NAME AS ValueName, " & _
      "  bline.QUANTITY, 1 AS USR$ISSPEND, 0 AS USR$ISEXPORT " & _
      SelectPart & _
      " FROM USR$INV_TOTRADE bill " & _
      "  LEFT JOIN GD_DOCUMENT d ON bill.DOCUMENTKEY = d.ID " & _
      "  LEFT JOIN USR$INV_TOTRADELINE bline ON bill.DOCUMENTKEY =
bline.MASTERKEY " & _
      "  LEFT JOIN INV_CARD c ON c.ID = bline.TOCARDKEY " & _
      "  LEFT JOIN GD_GOOD g ON g.ID = c.GOODKEY " & _
      "  LEFT JOIN GD_VALUE v ON g.VALUEKEY = v.ID " & _
      FromPart & _
      "WHERE bill.DOCUMENTKEY = :dockey "
  ' ïåðåîöåíêà
  elseif DocType = gdcBaseManager.GetIDByRUIDString("147013048_109092844")
then

    set qComp = Creator.GetObject(nil, "TIBSQL", "")
    qComp.Transaction = gdcBaseManager.ReadTransaction
    qComp.SQL.Text = _
      "select * from gd_company com where com.HEADCOMPANY = :headid and
com.CONTACTKEY = :conkey"
    qComp.ParamByName("headid").AsInteger =
gdcBaseManager.GetIDByRUIDString("151768829_2115439882")     '''' ID
ãëàâíîé îðãàíèçàöèè ÌÕÏ
    qComp.ParamByName("conkey").AsInteger =
gdcO.DetailLinks(0).FieldByname("FROM_USR$INV_PROVIDER").AsInteger
    qComp.ExecQuery
    ''''
    if not qComp.EoF and gdcO.FieldByName("USR$ISACTION").AsInteger = 0 then
      isOurCompany = true
    end if

    sqlGoodBill.SQL.Text = _
       "SELECT " & _
       "  bill.USR$DEPTKEY AS CONID, " & _
       "  g.ID, " & _
       "  g.ALIAS, " & _
       "  g.NAME, " & _
       "  g.USR$PF_ISWEIGHT, " & _
       "  g.BARCODE AS BARCODE, " & _
       "  g.USR$PF_ISFRAC, " & _
       "  c.USR$INV_COSTRETAILNCU, " & _
       "  (c.USR$INV_COSTBUYNCU+c.USR$INV_BUYNDSNCU) as Cost, " & _
       "  v.NAME AS ValueName, " & _
       "  0 AS QUANTITY, " & _
       "  1 AS USR$ISSPEND, 0 AS USR$ISEXPORT " & _
       SelectPart & _
       " FROM USR$INV_NEWCOST bill " & _
       "  LEFT JOIN GD_DOCUMENT d ON bill.DOCUMENTKEY = d.ID " & _
       "  LEFT JOIN USR$INV_NEWCOSTLINE bline ON bill.DOCUMENTKEY =
bline.MASTERKEY " & _
       "  LEFT JOIN INV_CARD c ON c.ID = bline.TOCARDKEY " & _
       "  LEFT JOIN GD_GOOD g ON g.ID = c.GOODKEY " & _
       "  LEFT JOIN GD_VALUE v ON g.VALUEKEY = v.ID " & _
       FromPart & _
       "WHERE bill.DOCUMENTKEY = :dockey "
  ' Åñëè îñòàòêè
  elseif DocType = 0 then
    sqlGoodBill.SQL.Text = _
      "SELECT " & _
      "  m.CONTACTKEY AS CONID, " & _
      "  g.ID, " & _
      "  g.ALIAS, " & _
      "  g.NAME, " & _
      "  g.USR$PF_ISWEIGHT, " & _
      "  g.BARCODE AS BARCODE, " & _
      "  g.USR$PF_ISFRAC, " & _
      "  MAX(c.USR$INV_COSTRETAILNCU) AS USR$INV_COSTRETAILNCU, " & _
      "  0 as Cost, " & _
      "  v.NAME AS VALUENAME, " & _
      "  SUM(m.BALANCE) as QUANTITY, " & _
      "  1 AS USR$ISSPEND, 0 AS USR$ISEXPORT " & _
      SelectPart & _
      " FROM  (" & _
      "          SELECT " & _
      "            m.CARDKEY, " & _
      "            m.CONTACTKEY, " & _
      "            SUM ( m.BALANCE ) AS BALANCE " & _
      "          FROM INV_BALANCE m " & _
      "          JOIN GD_CONTACT con ON m.CONTACTKEY  =  con.ID AND con.LB
 >=  :LB AND con.RB  <=  :RB " & _
      "          WHERE m.BALANCE  <>  0 " & _
      "          GROUP BY 1,2 " & _
      " " & _
      "          UNION ALL " & _
      " " & _
      "          SELECT " & _
      "            m.CARDKEY, " & _
      "            m.CONTACTKEY, " & _
      "            SUM ( m.CREDIT - m.DEBIT ) AS BALANCE " & _
      "          FROM INV_MOVEMENT m " & _
      "          JOIN GD_CONTACT con ON m.CONTACTKEY  =  con.ID AND con.LB
 >=  :LB AND con.RB  <=  :RB " & _
      "          WHERE m.DISABLED = 0 " & _
      "            AND m.MOVEMENTDATE  >  :EndDate " & _
      "          GROUP BY 1, 2) m "  & _
      "  LEFT JOIN INV_CARD c ON c.ID = m.CARDKEY " & _
      "  LEFT JOIN GD_GOOD g ON g.ID = c.GOODKEY " & _
      "  LEFT JOIN GD_VALUE v ON g.VALUEKEY = v.ID " & _
      FromPart & _
      " WHERE m.BALANCE  <>  0 " & _
      "  AND c.COMPANYKEY = <COMPANYKEY/> " & _
      "GROUP BY m.CONTACTKEY, g.ID, g.ALIAS , g.NAME, g.USR$PF_ISWEIGHT, "
& _
      "  BARCODE, g.USR$PF_ISFRAC, v.NAME, C.USR$INV_COSTRETAILNCU ,
C.USR$INV_COSTRETAILNCU  " & GroupPart & _
      "HAVING SUM(m.BALANCE) > 0 "
  elseif DocType = gdcBaseManager.GetIDByRUIDString("153236986_2115439882")
then
    '' Êàëüêóëÿöèÿ
    sqlGoodBill.SQL.Text = _
       "SELECT " & _
       "  doc.USR$DEPKEY AS CONID, " & _
       "  g.ID, " & _
       "  g.ALIAS, " & _
       "  g.NAME, " & _
       "  g.USR$PF_ISWEIGHT, " & _
       "  g.BARCODE AS BARCODE, " & _
       "  g.USR$PF_ISFRAC, " & _
       "  bline.USR$RETAILCOST as USR$INV_COSTRETAILNCU, " & _
       "  bline.USR$DISCCOST as Cost, " & _
       "  v.NAME AS ValueName, " & _
       "  0 AS QUANTITY, " & _
       "  1 AS USR$ISSPEND, 0 AS USR$ISEXPORT " & _
       " FROM USR$INV_CALCCARD doc " & _
       "  LEFT JOIN GD_DOCUMENT d ON doc.DOCUMENTKEY = d.ID " & _
       "  LEFT JOIN USR$INV_CALCCARDLINE bline ON doc.DOCUMENTKEY =
bline.MASTERKEY " & _
       "  LEFT JOIN USR$INV_NORMDISCARD nc on nc.ID = bline.USR$GOODNORMKEY
" & _
       "  LEFT JOIN GD_GOOD g ON g.ID = nc.USR$GOODKEY " & _
       "  LEFT JOIN GD_VALUE v ON g.VALUEKEY = v.ID " & _
       "WHERE doc.DOCUMENTKEY = :dockey "
       isOurCompany = true
  end if

  ' ñîçäàåì Ïðàéñ
  dim qPrice
  set qPrice = Creator.GetObject(nil, "TIBSQL", "")
  qPrice.Transaction = Transaction
  qPrice.SQL.Text = _
    " INSERT INTO USR$PF_PRICELIST (ID, USR$GOODKEY, USR$CODEDEPOT, " & _
    "   USR$PRICE, USR$PRICE2, USR$CODE, USR$ALIAS, USR$QUANTITY,
USR$BILLKEY) VALUES (:ID, :GOODKEY, :USR$CODEDEPOT, " & _
    "   :USR$PRICE, :USR$PRICE2, :USR$CODE, :USR$ALIAS, :USR$QUANTITY, :BK)
"

  ' îáíîâëÿåì Ïðàéñ
  dim qUpPrice
  set qUpPrice = Creator.GetObject(nil, "TIBSQL", "")
  qUpPrice.Transaction = Transaction
  qUpPrice.SQL.Text = _
    " SELECT SUM(USR$QUANTITY) AS USR$QUANTITY  FROM USR$PF_PRICELIST WHERE
USR$GOODKEY = :goodkey AND USR$CODEDEPOT = :CD " & _
    "  AND USR$CODE = :BARCODE /*AND USR$PRICE = :PRICE */"

'  dim qDelete
'  set qDelete = Creator.GetObject(nil, "TIBSQL", "")
'  qDelete.Transaction = Transaction
'  qDelete.SQL.Text = _
'    "DELETE FROM USR$PF_PRICELIST WHERE USR$GOODKEY = :goodkey AND
USR$CODEDEPOT = :CD AND USR$CODE = :BARCODE "

  dim qFeatures
  set qFeatures = Creator.GetObject(nil, "TIBSQL", "")
  qFeatures.Transaction = Transaction
  qFeatures.SQL.Text = _
    "INSERT INTO USR$PF_PRICEFEATURES(USR$PRICEINT, USR$NAME, USR$VALUE)
VALUES(:P, :N, :V) "

  if not Transaction.InTransaction then Transaction.StartTransaction

  except pfd_ExportFromDepotInServer_Exc(Transaction)

  dim DepotStr
  if DocType <> 0 then
    sqlGoodBill.ParamByName("dockey").AsInteger = ID
  else
    dim q, LB, RB
    LB = -2
    RB = -2
    set q = Creator.GetObject(nil, "TIBSQL", "")
    q.Transaction = gdcBaseManager.ReadTransaction
    q.SQL.Text = _
      "SELECT LB, RB " & _
      "FROM GD_CONTACT " & _
      "WHERE ID = :DepotKey "
    q.ParamByName("DepotKey").AsInteger = DepKey
    q.ExecQuery
    if not q.EoF then
      LB = q.FieldByName("LB").AsInteger
      RB = q.FieldByName("RB").AsInteger
    end if

    sqlGoodBill.ParamByName("Lb").AsInteger = LB
    sqlGoodBill.ParamByName("Rb").AsInteger = RB
    sqlGoodBill.ParamByName("EndDate").AsDateTime = EndDate
    q.Close
    q.SQL.Text = _
      "SELECT c.ID " & _
      "FROM GD_CONTACT p " & _
      "JOIN GD_CONTACT c ON c.LB >= p.LB AND c.RB <= p.RB AND c.CONTACTTYPE
= 4 " & _
      "WHERE p.ID = :DepotKey "
    q.ParamByName("DepotKey").AsInteger = DepKey
    q.ExecQuery
    DepotStr = ""
    while not q.EoF
      if DepotStr <> "" then DepotStr = DepotStr & ","
      DepotStr = DepotStr & q.FieldByName("ID").AsInteger
      q.Next
    wend
    if DepotStr = "" then DepotStr = "0"
  end if

  dim qDelete
  set qDelete = Creator.GetObject(nil, "TIBSQL", "")
  qDelete.Transaction = Transaction
  if DocType <> 0 then
    qDelete.SQL.Text = _
      "DELETE FROM USR$PF_PRICELIST WHERE USR$GOODKEY = :goodkey AND
USR$CODEDEPOT = :CD  "
'      "DELETE FROM USR$PF_PRICELIST WHERE USR$GOODKEY = :goodkey AND
USR$CODEDEPOT = :CD AND USR$CODE = :BARCODE /*AND USR$PRICE = :PRICE  */"
  else
    qDelete.SQL.Text = _
      "DELETE FROM USR$PF_PRICELIST WHERE USR$CODEDEPOT IN  (" & DepotStr &
")"
  end if
  sqlGoodBill.ExecQuery

  if sqlGoodBill.EoF then
    if not pf_Silent then
      call Application.MessageBox("Îñòàòêè íå íàéäåíû!", "Âíèìàíèå",
vbOkOnly + vbInformation  + vbSystemModal)
    end if
    Exit Function
  end if

  ' Ãåíåðàöèÿ ÈÄ íà óäàëåííîé ÁÄ
  dim qGenID
  set qGenID = Creator.GetObject(nil, "TIBSQL", "")
  qGenID.Transaction = Transaction
  qGenID.SQL.Text = _
    "SELECT " & _
    "GEN_ID(gd_g_unique, 1) + GEN_ID(gd_g_offset, 0) AS NewID " & _
    "FROM RDB$DATABASE "



  dim qGetDB
  set qGetDB = Creator.GetObject(nil, "TIBSQL", "")
  qGetDB.Transaction = Transaction
  qGetDB.SQL.Text = _
    "SELECT gen_id(gd_g_dbid, 0) AS DBID FROM rdb$database"

  dim GoodKey, WasError, gdcGood
  set gdcGood = Creator.GetObject(nil, "TgdcGood", "")
  gdcGood.SubSet = "OnlySelected"

  WasError = false
  dim NewId, DBID

  qGetDB.Close
  qGetDB.ExecQuery
  DBID = qGetDB.FieldByName("DBID").AsInteger

  dim Quant, j

  ' åñëè ýòî îñòàòêè, íóæíî ïîëíîñòüþ î÷èñòèòü ïðàéñ ïî ýòîìó ïîäðàçäåëåíèþ
  if DocType = 0 then
    qDelete.Close
    qDelete.ExecQuery
  end if


  while not sqlGoodBill.EoF
    if pf_ServerWithDepot then
      Goodkey = sqlGoodBill.FieldByName("id").AsInteger
    else
      GoodKey = pfd_FindOrAddGood(sqlGoodBill.FieldByName("ID").AsInteger,
Transaction, false)
    end if

    if GoodKey > 0 then
      if sqlGoodBill.FieldByName("USR$ISSPEND").AsInteger = 1 and _
        sqlGoodBill.FieldByName("USR$ISEXPORT").AsInteger = 0 then

        err.Clear
  '      on error resume next
          Quant = 0
          ' Åñëè íå îñòàòêè
          if DocType <> 0 then
            qUpPrice.Close
            qUpPrice.ParamByName("goodkey").AsInteger = Goodkey
            qUpPrice.ParamByName("CD").AsInteger =
sqlGoodBill.FieldByName("CONID").AsInteger
            qUpPrice.ParamByName("BARCODE").AsString =
sqlGoodBill.FieldByName("BARCODE").AsString
            'qUpPrice.ParamByName("PRICE").AsCurrency =
sqlGoodBill.FieldByName("USR$INV_COSTRETAILNCU").AsCurrency
            qUpPrice.ExecQuery
            Quant = qUpPrice.FieldByName("USR$QUANTITY").AsCurrency


            qDelete.Close
            qDelete.ParamByName("goodkey").AsInteger = Goodkey
            qDelete.ParamByName("CD").AsInteger =
sqlGoodBill.FieldByName("CONID").AsInteger
'            qDelete.ParamByName("BARCODE").AsString =
sqlGoodBill.FieldByName("BARCODE").AsString
            'qDelete.ParamByName("PRICE").AsCurrency =
sqlGoodBill.FieldByName("USR$INV_COSTRETAILNCU").AsCurrency
            qDelete.ExecQuery

          end if

          qGenID.Close
          qGenID.ExecQuery
          NewId =  qGenID.FieldByName("NewID").AsInteger
          qPrice.Close
          qPrice.ParamByName("ID").AsInteger =  NewId
          qPrice.ParamByName("GOODKEY").AsInteger = _
            GoodKey
          qPrice.ParamByName("USR$CODEDEPOT").AsInteger = _
            sqlGoodBill.FieldByName("CONID").AsInteger

          qPrice.ParamByName("USR$PRICE").AsCurrency = _
            sqlGoodBill.FieldByName("USR$INV_COSTRETAILNCU").AsCurrency

          ''''' Åñëè ïîñòàâùèê - îðãàíèçàöèÿ ÌÕÏ, òî çàïîëíÿåì âòîðóþ öåíó
= ïîêóïíàÿ+íäñ
          if isOurCompany then
            qPrice.ParamByName("USR$PRICE2").AsCurrency = _

InvOptions.invRound(sqlGoodBill.FieldByName("cost").AsCurrency,
Mat_RoundType, 50)
          end if
          ''''''''''''''

'          qPrice.ParamByName("USR$CODE").AsString = _
'            sqlGoodBill.FieldByName("BARCODE").AsString

          qPrice.ParamByName("USR$ALIAS").AsString = _
            sqlGoodBill.FieldByName("ALIAS").AsString

          qPrice.ParamByName("USR$QUANTITY").AsCurrency = _
            sqlGoodBill.FieldByName("QUANTITY").AsCurrency + Quant

          if ID > 0 then
            qPrice.ParamByName("BK").AsInteger = ID
          else
            qPrice.ParamByName("BK").AsVariant = null
          end if

          qPrice.ExecQuery
          ' Åñëè Íàêëàäíàÿ íà ïîëó÷åíèå..
          if DocType =
gdcBaseManager.GetIDByRUIDString("147010993_109092844") then
            if not OurTransaction.InTransaction then
OurTransaction.StartTransaction
            qIsExp.Close
            qIsExp.ParamByName("dockey").AsInteger = ID
            qIsExp.ParamByName("goodkey").AsInteger = GoodKey
            qIsExp.ParamByName("cost").AsCurrency =
sqlGoodBill.FieldByName("USR$INV_COSTRETAILNCU").AsCurrency
            qIsExp.ParamByName("q").AsInteger =
sqlGoodBill.FieldByName("QUANTITY").AsCurrency
            qIsExp.ExecQuery
          end if

          if UBound(FeatureNamesArr) >= 0 then
            j = 1
            while j <= (UBound(FeatureNamesArr) + 1)
              if not sqlGoodBill.Fields(9 + j).IsNull then
                qFeatures.Close
                qFeatures.ParamByName("P").AsInteger = NewID
                qFeatures.ParamByName("N").AsString = FeatureNamesArr(j - 1)
                qFeatures.ParamByName("V").AsString =
Left(sqlGoodBill.Fields(9 + j).AsString, 120)
                qFeatures.ExecQuery
              end if
              j = j + 1
            wend
          end if
  '      on error goto 0
      end if
      else
        WasError = True
        call
gdcGood.AddToSelectedID(sqlGoodBill.FieldByName("ID").AsInteger)
      end if
    sqlGoodBill.Next
  wend

  if Assigned(gdcO) then
    gdcO.Edit
    gdcO.FieldByName("USR$PFD_DELIVERED").AsInteger = 1
    gdcO.Post
    gdcO.Refresh
  end if

    'åñëè ÒÌÖ íåò, åãî íóæíî ïåðåíåñòè íà ÁÄ êàññîâîãî ñåðâåðà âðó÷íóþ
  if WasError then
    if Application.MessageBox("Íåêîòîðûå ÒÌÖ íå íàéäåíû íà áàçå êàññîâîãî
ñåðâåðà. " & VBCr & _
        "Èõ íåîáõîäèìî ïåðåíåñòè âðó÷íóþ! Ñôîðìèðîâàòü ôàéë äàííûõ?", _
         "Âíèìàíèå", mb_YesNo or vbSystemModal or mb_IconError) = vbYes then
      gdcGood.Open
      dim gdcSetting, gdcSettingPos
      set gdcSetting = Creator.GetObject(nil, "TgdcSetting", "")
      set gdcSettingPos = Creator.GetObject(nil, "TgdcSettingPos", "")
      dim dsMaster
      set dsMaster = Creator.GetObject(nil, "TDataSource", "")
      dsMaster.DataSet = gdcSetting

      gdcSettingPos.MasterSource = dsMaster
      gdcSettingPos.MasterField = "ID"
      gdcSettingPos.DetailField = "SETTINGKEY"
      gdcSettingPos.SubSet = "BySetting"

      gdcSetting.Open
      gdcSettingPos.Open
      gdcSetting.Insert
      gdcSetting.FieldByName("NAME").AsString = _
        CStr(Year(Now)) & "_" & Right("0" & CStr(Month(Now)), 2)& "_" &
Right("0" & CStr(Day(Now)), 2)
      gdcSetting.FieldByName("MODIFYDATE").AsDateTime = Now
      gdcSetting.Post

      while not gdcGood.EoF
        call gdcSettingPos.AddPos(gdcGood, false)
        gdcGood.Next
      wend
      if gdcSettingPos.RecordCount > 0 then
        on error resume next
          call gdcSetting.SaveSettingToBlob
        on error goto 0
        call gdcSetting.SaveToFile("")
      else
        gdcSetting.Delete
      end if
    end if
    Transaction.RollBack
  end if
  gdcGood.Close
  if  OurTransaction.InTransaction then
    OurTransaction.Commit
  end if
  if  Transaction.InTransaction then
    Transaction.Commit
    if not pf_Silent then
      call Application.MessageBox("Ýêñïîðò òîâàðà çàâåðøåí!", _
         "Âíèìàíèå", mb_Ok or vbSystemModal or mb_IconInformation)
    end if
  end if

end function

sub pfd_ExportFromDepotInServer_Exc(Transaction)
  if Transaction.InTransaction then Transaction.Rollback
end sub

function  pfd_ExportFromDepotInServer_GetClauses(Creator, NeedGroupPart)
  dim q
  set q = Creator.GetObject(nil, "TIBSQL", "")
  q.Transaction = gdcBaseManager.ReadTransaction
  q.SQL.Text = _
    "SELECT " & _
    "  cl.USR$NAME AS FeatureName, " & _
    "  rf.RELATIONNAME, " & _
    "  rf.FIELDNAME, " & _
    "  d.REFKEYFIELD, " & _
    "  d.REFLISTFIELD, " & _
    "  d.REFRELATION, " & _
    "  CASE rf.RELATIONNAME " & _
    "    WHEN 'GD_GOOD' THEN 'g' " & _
    "    WHEN 'INV_CARD' THEN 'c' " & _
    "    ELSE '' " & _
    "  END AS CondAlias " & _
    "FROM USR$PFD_CODESETTINGS cl " & _
    "LEFT JOIN AT_RELATION_FIELDS rf ON rf.ID  =  cl.USR$FIELDKEY " & _
    "LEFT JOIN USR$PFD_P_GET_REF_PARAMS(rf.FIELDSOURCEKEY, rf.FIELDNAME,
rf.RELATIONNAME) d ON 1 = 1 " & _
    "LEFT JOIN RDB$RELATION_FIELDS rdb_f ON rdb_f.RDB$FIELD_NAME =
IIF(d.REFLISTFIELD IS NULL, rf.FIELDNAME, d.REFLISTFIELD) " & _
    "                                   AND rdb_f.RDB$RELATION_NAME =
IIF(d.REFRELATION IS NULL, rf.RELATIONNAME, d.REFRELATION) "
  q.ExecQuery
  dim TabAlias, SelectPart, FromPart, GroupPart, i, RefFieldName,
 FeatureNames
  SelectPart = ""
  FromPart = ""
  GroupPart = ""
  FeatureNames = ""
  i = 1
  while not q.EoF
    if SelectPart <> "" then
      SelectPart = SelectPart &  VBCR
    end if
    TabAlias = Trim(q.FieldByName("CondAlias").AsString)
    if not q.FieldByName("REFRELATION").IsNull then
      FromPart = FromPart & VBCr & _
          "LEFT JOIN " & Trim(q.FieldByName("REFRELATION").AsString) & "
ref"   & i & " ON ref"   & i & "." &
Trim(q.FieldByName("REFKEYFIELD").AsString) & " = " & TabAlias & "." &
 Trim(q.FieldByName("FIELDNAME").AsString) & " "
      RefFieldName = " ref" & i & "." &
Trim(q.FieldByName("REFLISTFIELD").AsString )
    else
      RefFieldName = TabAlias & "." &
Trim(q.FieldByName("FIELDNAME").AsString)
    end if
    SelectPart = SelectPart & ", " & RefFieldName & " AS Group" & i
    if NeedGroupPart then
      GroupPart = GroupPart &  "," &  RefFieldName & " "
    end if
    if FeatureNames <> "" then FeatureNames = FeatureNames & ";"
    FeatureNames = FeatureNames &
Trim(q.FieldByName("FeatureName").AsString)
    i = i + 1
    q.Next
  wend
  pfd_ExportFromDepotInServer_GetClauses = Array(SelectPart, FromPart,
GroupPart, FeatureNames)
end function

30 апреля 2015 г., 20:54 пользователь alexandra-gsoftware <
notifications@github.com> написал:

> макрос пересчета начислений немного косячный. Он на отдельной транзакции
> очищает начисления по табелю, считает заново нужное начисление, закидывает
> ручным вводом разницу между тем, что сейчас посчитано и тем, что было, и
> откатывает транзакцию. А при расчете подоходного идет запись в
> дополнительные таблицы (т.е. с откатыванием транзакции проблема)... там
> надо очень хорошо подумать, как это грамотно переделать.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/11#issuecomment-97897493>
> .
>



-- 
 С уважением,
 *Васильев Михаил* .

**Comment by YRozmysl** [comment]
Наверное, немножко не по адресу.
