### ISSUE TITLE
Договора и акты, дата зачисления.

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/gedemin-apps#13]
Имеет смысл доработать документ "Договора и акты", добавив в него еще и поле "Дата зачисления". На текущий момент в документе есть и заполняется только поле "Дата начисления" причем всегда "Дата начисления" = "Дата зачислнеия". На практике, часто бывает, когда "Дата начисления" <> "Дата зачислнеия".  Можно сделать следующим образом. Если поле "Дата зачисления" заполенно,  то берем его, его оно пустое, то  "Дата начисления" = "Дата зачислнеия"

**Comment by olga-hozyanin** [comment]
это точно мне адресовано?

С уважением,

Хозянин Ольга


27 апреля 2015 г., 16:49 пользователь Yury Rozmysl <notifications@github.com

**Comment by NikolayUkleyko** [comment]
Да, Оля, тебе адресовано. Приступай к работе.
  )
