### ISSUE TITLE
Недопустимый подтип EVT_MACROSGROUP для класса TgdcAttrUserDefined

### ISSUE THREAD

**Issue by zholnerovich** [GoldenSoftwareLtd/gedemin-apps#14]
В ПИ GS.PositiveCash.Потроха.Глобальные макросы присутствует недопустимый подтип EVT_MACROSGROUP для класса TgdcAttrUserDefined. Надо его убрать.

**Comment by hirurg-lybitel** [comment]
well done!

**Comment by alexandra-gsoftware** [comment]
Хм а как у вас это получилось? Или это где-то в коде?

**Comment by zholnerovich** [comment]
Проверил, теперь устанавливается.
