### ISSUE TITLE
usrg_gdcAUDExtraGood: Cannot perform this operation on an open dataset

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#16]
Если из под Делфи запускать, то видно такое исключение:

Exception class EDatabaseError with message 'usrg_gdcAUDExtraGood: Cannot perform this operation on an open dataset'.

Надо посмотреть на эталоне. Похоже, что на диалоге товара этот датасет сохранен в открытом виде. Надо бы закрыть и открывать программно по мере необходимости.

**Comment by alexandra-gsoftware** [comment]
ок, но потом нажмет кто-нить ctrl alt e, и привет
