### ISSUE TITLE
ЗП. Сводная ведомость (Новая)

### ISSUE THREAD

**Issue by hjamesgs** [GoldenSoftwareLtd/gedemin-apps#17]
Сделать больше размерность поля "Наименование начисления"
+ установить в шаблоне признак "растягиваемый"

**Comment by YRozmysl** [comment]
используй отчет Сводная ведомость (по подразделениям) с детализацией, который по своей сути точно такой же, там больше  информации. и в шаблоне там стоит уже признак "растягиваемый"
