### ISSUE TITLE
Похоже, одинаковые РУИДы у ПИ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#19]
16:46:56 Пространство имен: "GS.Общее.Функции работы с датой" содержится в файлах:
1: g:\golden\gedemin-apps\Общие\GS.Общее.Функции работы с датой.yml
2: g:\golden\gedemin-apps\Общие\GS.Общее.Функция определения количества дней в месяце.yml
Только первый файл будет обработан!

**Comment by alexandra-gsoftware** [comment]
2е нужно удалить
