### ISSUE TITLE
Can not login twice !!!

### ISSUE THREAD

**Issue by yoannawx** [GoldenSoftwareLtd/gedemin-apps#22]
Ошибку можно воспроизвести на базе розница-торговля-склад. Возникает при вызове макроса Выгрузить на весы документа Форма удаленного просмотра  (хотя вызывается под пользователем Synchronizer).

**Comment by gsbelarus** [comment]
Это не ошибка. Так устроен Гедымин, что не дает из макроса создать еще один, новый экземпляр программы. Я смотрю по коду. В чем там смысл? Мы уже подключены и создаем еще один экземпляр к этой же БД. Зачем? Не проще ли взять и вызвать макросы в ЭТОМ, ТЕКУЩЕМ экземпляре?
