### ISSUE TITLE
Формат сумм

### ISSUE THREAD

**Issue by hirurg-lybitel** [GoldenSoftwareLtd/gedemin-apps#23]
Надо, чтобы на уровне экзешника присутствовало разбиение вводимого числа на тысячные при вводе его в компонент TxDBCalculatorEdit, т.е. форматирование числа в реальном времени, а не только после его сохранения.

**Comment by gsbelarus** [comment]
Сюда постить только по прикладным решениям. А по экзешнику у нас отдельный проект и отдельный, теперь, треккер:

https://github.com/GoldenSoftwareLtd/gedemin/issues
