### ISSUE TITLE
Стандартные поля затесались в ПИ

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#24]
USR$MN_ACCUMULATOR.ID

USR$INV_INVENTLINE.TOQUANTITY

USR$INV_INVENTLINE.FROMQUANTITY

USR$INV_INVENTLINE.FROMCARDKEY

USR$INV_INVENTLINE.MASTERKEY

 USR$INV_INVENTLINE.DOCUMENTKEY

USR$INV_INVENT.DOCUMENTKEY

USR$INV_REFFORMTORG.ID 

USR$MN_PAYMENT.ID

**Comment by yoannawx** [comment]
исправлено
