### ISSUE TITLE
Новая печатная форма расчетного листка

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#25]
1) слишком маленькое поле вверху страницы. Не пропечатывается принтером первый листок на странице.

2) отработано дней: 22, отраотано часов: 176

а не так как сейчас выводится, некрасиво

3) План: 22 дн. / 176 ч

а не так как сейчас выводится

4) Вместо Мес. лучше М-ц.

5) личный номер лучше подравнять по вертикали с ФИО

**Comment by YRozmysl** [comment]
Используйте "Расчётный листок (развернутый)" именно эта печатная форма дорабатывается постоянно и редактируется.
