### ISSUE TITLE
Учет спецодежды. Консервация и расконсервация. Цена учета

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#27]
Исследователь > Учет спецодежды > Консервация > Консервация спецодежды и Расконсервация спецодежды.
  При выборе спецодежды из остатков значение в поле Цена учета, руб. (TO_USR$INV_COSTACCNCU) равно значению покупной цены из INV_CARD (USR$INV_COSTBUYNCU). В противном случае значение в поле Цена учета, руб. (TO_USR$INV_COSTACCNCU) равно 0. Зачем так сделано ? Тем более это было сделано аж в 2005 г. Это было сделано осознанно.

sub TgdcInvDocumentLine147533177_50219829DoBeforePost(Self)
'*** Данный код необходим для вызова кода определенного в gdc-классе.***
'*** При его удаления  возможно нарушение  правильной работы системы.***
  call Inherited(Self, "DoBeforePost", Array(Self))
'***               Конец кода поддержки gdc-класса.                  ***
  Self.FieldByName("TO_USR$FA_USAGEKEY").AsInteger = gdcBaseManager.GetIDByRUIDString("147195392_50219829")
  Self.FieldByName("TO_USR$WC_CONSERVATIONDOCKEY").AsVariant = NULL
  Self.FieldByName("TO_USR$WC_CONSERVREVDOCKEY").AsInteger = Self.ID
  set CREATOR = new TCreator
  set ibsql = Creator.GetObject(null,"TIBSQL", "")
  ibsql.Transaction = gdcBaseManager.ReadTransaction
  ibsql.SQL.Text = "select CARD.USR$INV_COSTBUYNCU as BuyCost " & _
    "from INV_CARD CARD WHERE CARD.ID = " + _
    Self.FieldByName("FROMCARDKEY").AsString
  ibsql.ExecQuery

  Self.FieldByName("TO_USR$INV_COSTACCNCU").AsInteger = _
   ibsql.FieldByName("BuyCost").AsInteger
end sub

  При отражении поступления спецодежды на склад через документ 01. Накладная на получение материалов, ОС, МБП цену покупки обычно заполняют, хотя она особого смысла при учете материальных ценностей не несет (в торговле иначе). Для учета важна цена учета.
  При отражении остатков спецодежды на складе и в эксплуатации через документ 2. Ввод остатков спецодежды в эксплуатацию по умолчанию цену покупки заполнить нельзя. Только цену учета.

**Comment by MIchaelShoihet** [comment]
Ерунда какая-то, цена учета в данном документе менятся не должна. Надо удалять этот код. И цена учета должна быть признаком существующей карточи и только из признаков новой карточки ее надо убрать

**Comment by NikolayUkleyko** [comment]
Поэтому я и спрашиваю. Признаки настроены корректно, а получается такое.
Я за то, чтобы значение цены учета бралось из признаков существующей
карточки, а не присваивалось значением покупной цены.
  Поправим.

  Спасибо !

**Comment by NikolayUkleyko** [comment]
Внесены доработки и сохранены изменения.
