### ISSUE TITLE
Основные средства. ОС. Акт ввода в эксплуатацию. Проводка на сумму НДС

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#28]
Исследователь > Основные средства > Акт ввода в эксплуатацию > ОС. Акт ввода в эксплуатацию.
  Зачем в документе выделяется сумма НДС и формируется проводка (Дт 01... - Кт 18.01.01) ? Мне не совсем понятен смысл. Может быть, здесь хотели отразить сразу же перевод суммы НДС, подлежащей уплате в НДС, уплаченный. Хотя, зачем здесь счет по дебету 01...? Увеличивается оборот по дебету счета 01... Я давно на это смотрю. Необходимо разобраться.
![1](https://cloud.githubusercontent.com/assets/11497453/8880439/8f9be364-3241-11e5-9901-e2c746a16552.png)
![2](https://cloud.githubusercontent.com/assets/11497453/8880440/9042df84-3241-11e5-8965-0321549b9470.png)

**Comment by MIchaelShoihet** [comment]
Здесь все правильно. Раньше в отдельных случаях сумма НДС по ОС в момент ввода в эксплуатацию включалась в стоимость ОС, а не шла в зачет. Сейчас пока таких ситуаций нет, но ничто не вечно под луной. Это поле заполняется именно в таком случае, во всех остальных случаях оно не заполняется.

**Comment by NikolayUkleyko** [comment]
Получается двоякость ситуации. По бухгалтерскому учету балансовая стоимость основного средства состоит из балансовой цены и суммы НДС, а по складскому учету - только из балансовой цены. Получается разница.

**Comment by MIchaelShoihet** [comment]
Вообще проводки должны были быть настроены 01 - 08 цена покупная 01 - 18 цена НДС, а в балансовую стоимость попадать сумма. Но мудрить сейчас не надо, это поле надо скрыть и забыть про него. Вернется законодательство, тогда будем думать.

**Comment by NikolayUkleyko** [comment]
Спасибо.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
