### ISSUE TITLE
Etalon_business. Торговля. 05. Возврат товара от покупателей. Ошибка при выборе остатков

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#29]
Исследователь > Торговля > 05. Возврат товара от покупателей.
  При выборе остатков программа выдает окно с сообщением об ошибке.  
![1 05](https://cloud.githubusercontent.com/assets/11497453/8906033/befcdd82-3473-11e5-8a75-f5c1a4e8305f.png)
![2 05](https://cloud.githubusercontent.com/assets/11497453/8906035/c12e246c-3473-11e5-9a28-e84829d494ca.png)

**Comment by alexandra-gsoftware** [comment]
сегодня закину вместе с последними изм по торговле
