### ISSUE TITLE
Etalon_business. Валютная торговля. 04. Счета-фактуры валютные (оптовая торговля). Ошибка при формировании накладной

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#30]
Исследователь > Торговля > Валютная торговля > 04. Счета-фактуры валютные (оптовая торговля).
  При попытке формирования накладной на отпуск на основании счет-фактуры программа выдает окно с сообщением об ошибке. Непосредственно в самой накладной выбор остатков выполняется без ошибок и документ сохраняется корректно.
![1 -](https://cloud.githubusercontent.com/assets/11497453/8906551/3d53ab4e-3478-11e5-9803-30a6413659f2.jpg)
![2 -](https://cloud.githubusercontent.com/assets/11497453/8906553/434f974c-3478-11e5-9153-729e6b6c3e24.jpg)
  Здесь речь идет о реквизитах Класс груза (USR$CARGOCLASS) и Код груза (USR$CARGOCODE). Я заполнил такие реквизиты в док-е 01. Накладная на получение импортного товара. Ничего это не дало.
  Посмотрел, что реквизиты Класс груза и Код груза не являются складскими признаками. Они просто добавлены в таблицу USR$INV_ADDWBILLLINE и USR$INV_ADDWBILLLINE. В таблице USR$INV_BILL (документ 04. Счета-фактуры валютные (оптовая торговля)) такие реквизиты отсутствуют. Возникли вопросы:
1. Почему поля Класс груза (USR$CARGOCLASS) и Код груза (USR$CARGOCODE) не были добавлены в таблицу INV_CARD ?
2. Если, такие поля задумывались, не как складские признаки, а как поля, то почему они не были добавлены в таблицу USR$INV_BILL (документ 04. Счета-фактуры валютные (оптовая торговля)) ?
3. Обратите внимание на текст функции

Option Explicit
'Заполняем класс груза и код груза в док-тах торговли
sub inv_FillCargoInfo (gdcInvDocumentLine)

  if not Assigned(gdcInvDocumentLine.FindField("usr$cargoclass")) then exit sub
  if not Assigned(gdcInvDocumentLine.FindField("usr$cargocode")) then exit sub

  dim Creator, ibsql
  set Creator = new TCreator
  set ibsql = Creator.GetObject(nil, "TIBSQL", "")
  ibsql.Transaction = gdcBaseManager.ReadTransaction
  ibsql.SQL.Text = _
    "SELECT FIRST 1 " & _
    "  doc.DOCUMENTDATE, " & _
    "  sl.USR$CARGOCLASS, " & _
    "  sl.USR$CARGOCODE " & _
    "FROM INV_CARD card " & _
    "JOIN USR$INV_SELLBILLLINE sl ON sl.FROMCARDKEY = card.ID " & _
    "LEFT JOIN GD_DOCUMENT doc ON doc.ID = sl.MASTERKEY " & _
    "WHERE card.GOODKEY = :GoodKey " & _
    "ORDER BY doc.DOCUMENTDATE DESC "

  ibsql.ParamByName("goodkey").AsInteger = gdcInvDocumentLine.FieldByName("goodkey").AsInteger
  ibsql.ExecQuery
  if not ibsql.EOF then
    gdcInvDocumentLine.FieldByName("usr$cargoclass").AsCurrency =_
      ibsql.FieldByName("usr$cargoclass").AsCurrency
    gdcInvDocumentLine.FieldByName("usr$cargocode").AsCurrency =_
      ibsql.FieldByName("usr$cargocode").AsCurrency
  end if
  ibsql.Close
End sub
  Пробовал выполнить SQL-запрос - результат пустой.
  Зачем, так было усложнять задачу ? Через складские признаки было бы гораздо проще и корректнее.

**Comment by alexandra-gsoftware** [comment]
так работало всегда, я просто вынесла в отдельную ф-ю. Тоже сегодня подправлю.
