### ISSUE TITLE
Основные средства. Комплектация/Разукомплектация и документ ОС. Допоступление/Списание затрат

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#31]
Исследователь > Основные средства > ОС. Комплектация > ОС. Комплектация, ОС. Разукомплектация и  ОС. Допоступление/Списание затрат.
  При формировании записи в документе ОС. Допоступление/Списание затрат на основании документов ОС. Комплектация, ОС. Разукомплектация необходимо предусмотреть следующее:
1. Отображение диалогового окна добавляемой записи в документе ОС. Допоступление/Списание затрат. Сейчас генерация документов работает в тихом режиме.
2. В диалоговом окне добавляемой записи в документе ОС. Допоступление/Списание затрат в поле Дата документа по умолчанию должна быть значение даты документа из документов ОС. Комплектация, ОС. Разукомплектация. Так как, операции Комплектация/Разукомплектация > Допоступление/Списание затрат едины во времени, то есть от одной даты.

**Comment by MBurakina** [comment]
Я бы еще в позиции ОС.Допоступление/Списание затрат добавила поле-ссылку на родительский документ (ОС. Комплектация, ОС. Разукомплектация). На данный момент можно сколько угодно раз создать списание с ОСа, заминусовать его стоимость и т.д.  Тогда и для п. 2 можно будет точно найти нужное допоступление/списание.

**Comment by NikolayUkleyko** [comment]
Сейчас можно сколь угодно раз сформировать запись в документе ОС. Допоступление/Списание затрат на основании документов ОС. Комплектация, ОС. Разукомплектация.
  Такая проверка необходима.
  Хорошо бы еще выводить соответствующее сообщение.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Все работает корректно.
  Большое спасибо, Марина !
