### ISSUE TITLE
Материальный склад. Комплектация ТМЦ/Разукомплектация ТМЦ. Изменение учетной цены комплекта

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#32]
Исследователь > Материальный склад > 12. Комплектация ТМЦ/13. Разукомплектация ТМЦ.
  При формировании комплекта ТМЦ из нескольких комплектующих ТМЦ цена учета конечного комплекта меняется в большую сторону, а при разукомплектации - в меньшую. На сегодняшний день изменение учетной цены и формирование бухгалтерских проводок не предусмотрено, а должно. Предлагаю предусмотреть отражение изменения учетной цены как по складскому учету, так и по бухгалтерскому учету в отдельном документе 08. Переоценка материалов. Подобный механизм реализован в подсистеме по учету основных средств (документы Комплектакция/Разукомплектация > Допоступление/Списание затрат).Так будет наиболее корректно. Общая идея.
  Предусмотреть следующее:
1. На верхнюю панель инструментов документов Комплектация ТМЦ/Разукомплектация ТМЦ добавить кнопки Создать записи в документе 08. Переоценка материалов.
2. При добавлении записей в документ 08. Переоценка материалов на основании записей из документов Комплектация ТМЦ/Разукомплектация ТМЦ выводить диалоговое окно. 
3. Предусмотреть, чтобы в добавляемой записи в документе 08. Переоценка материалов дата документа по умолчанию равнялась дате документов Комплектация ТМЦ/Разукомплектация.

  Кто не согласен, пусть выскажет свое мнение.

**Comment by alexandra-gsoftware** [comment]
может, в самой комплектации менять?

**Comment by NikolayUkleyko** [comment]
Если, предусмотреть возможность непосредственно в документах 12. Комплектация ТМЦ/13. Разукомплектация ТМЦ автоматический расчет новой цены учета на сумму добавленных/удаленных комплектующих с последующим формирование бухгалтерских проводок, то будет отлично.
  Тогда, напрашивается предложение, чтобы документы комплектации/разукомплектации по основным средствам переделать так, как это сделано в материальном складе. Тогда, не надо разрывать документы комплектации/разукомплектации и изменения учетной цены.

**Comment by MIchaelShoihet** [comment]
Данные документы предназначены для учета драгметаллов и на стоимость обычно не влияют. Я бы ничего не делал. Вообще новый функционал надо добавлять в случае крайней необходимости. Надо добиться чтобы в рамках существующего функционала всё работало без ошибок.

**Comment by MIchaelShoihet** [comment]
Вообще в плане методологии данные документы используются в случае ремонта материалов, когда заменяемые запчасти содержат драгметаллы отличающиеся от оригинальных. Т.к. стоимость этих запчастей всегда идет в затраты и только для ОС иногда они идут на увеличение стоимости. Все остальные изменения должны идти через акт переработки.

**Comment by NikolayUkleyko** [comment]
Хорошо.
  Ничего дорабатывать не будем.
  Спасибо.
