### ISSUE TITLE
Валютная торговля. 07. Возврат поставщику импортного товара

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#34]
Исследователь > Торговля > Валютная торговля.
  По данному документу отсутствует типовая хоз. операция.
  Так и должно быть ?
  Я считаю, что по данному документу должны формироваться бухгалтерские проводки Дт 41.01 - Кт 60 на отрицательную сумму.
  Высказывайтесь.

**Comment by MIchaelShoihet** [comment]
Да должна быть проводка. Счет дебета из позиции, счет кредита из шапки. И с минусом.

**Comment by NikolayUkleyko** [comment]
Создана типовая проводка 'Возврат импортного товара' (Оптово-розничный склад > Возврат поставщику товаров).
  Почему-то, после установки ПИ 'Проводки валютного оптово_розничного склада' типовая хоз. операция 'Возврат импортного товара' не привязана к типовому документу. На самом деле привязана.
  Аналогично и по типовой хоз. операции 'Возврат экспортного товара' (Оптово-розничный склад > 04. Возврат товара от покупателей > Реализация по отгрузке)  по документу '05. Возврат товара от экспортного покупателя'.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
