### ISSUE TITLE
Нужен ли бухгалтерский план счетов в эталоне?

### ISSUE THREAD

**Issue by stasgm** [GoldenSoftwareLtd/gedemin-apps#37]
Сейчас на эталоне (который на сайте) уже есть план счетов. 
В ПИ "Проводки валютного склада.." (а может ещё куда-то) входит также план счетов (но немного другой). Во время установки ПИ "розничная торговля\общкеит" на чистую базу возникают конфликтные ситуации связанные с дублированием номера счёта.

Для каких целей добавлен план счетов в эталон? Разве он не должен быть в ПИ?

**Comment by gsbelarus** [comment]
А что за ошибки? По идее не должны возникать т.к. при загрузке номера счетов сопостовляются по номеру.

**Comment by NikolayUkleyko** [comment]
В базе данных (комплексная автоматизация) с сайта всегда был план счетов.
  Сейчас новый план счетов находится строго в одном ПИ Бухгалтерские счета.
  Если, были выявлены некоторые несоответствия, то небходимо пересохранить ПИ Розничная торговля/общепит согласно нового плана счетов.
  По поводу вопроса: "Для каких целей добавлен план счетов в эталон?". Так сделано не мной. Вообще, если представить, то проводки без плана счетов вряд ли установятся. План счетов первичен.

**Comment by yoannawx** [comment]
ошибки возникают при установке как раз ПИ Бухгалтерские счета на эталонную
базу, общепит и торговля ни при чем

С уважением,
Жанна Хилько,
специалист по внедрению и сопровождению
8-029-376-13-43
icq 342682323

3 августа 2015 г., 12:33 пользователь NikolayUkleyko <
notifications@github.com> написал:

**Comment by NikolayUkleyko** [comment]
Не должны.
  Какого характера ошибки ? Скриншоты скиньте. Я же не бабушка. У меня все устанавливалось корректно.
  Не надо так пугаться всех ошибок. Некоторые из них просто носят информационный характер. Ничего они не нарушают.

**Comment by stasgm** [comment]
Коля, мы не пугаемся ошибок. Мы видим с Жанной несоответствие, которое лучше устранить, а не махать на рукой - да и чёрт с ошибкой. Когда я говорю эталон, я имею в виду не комплексную автоматизацию, а etalon.fdb т.е. пустой эталон. А вопрос "для каких целей..." не адресован конкретно тебе, адресован любому, кто ответит. 
Мне казалось, что эталон не должен содержать справочников, но план счетов на нём стоит.

**Comment by stasgm** [comment]
etalon_complete.fdb

![image](https://cloud.githubusercontent.com/assets/8355925/9035955/73dee2ce-39e5-11e5-9ff2-d074a0e00de0.png)

etalon.fdb

![image](https://cloud.githubusercontent.com/assets/8355925/9035968/a54158ba-39e5-11e5-86af-8fa9b33f7170.png)

А вот ошибки при установке ПИ на etalon.fdb

![image](https://cloud.githubusercontent.com/assets/8355925/9036026/22d1a384-39e6-11e5-96e6-90527fb0fb57.png)

![image](https://cloud.githubusercontent.com/assets/8355925/9036032/3632ec80-39e6-11e5-8677-4aeb6a3f513e.png)

**Comment by NikolayUkleyko** [comment]
Я вовсе не про отмашку. Про то, что ошибку, конечно ж устранят. Теперь есть скриншоты и все выяснится.
  Мне самому интересно зачем в пустой эталон включать план счетов ? С базой business и etalon_complete порядок. Скажу то, что в базу данных etalon.fdb (пустой эталон) план счетов закидывается не через ПИ, а через совершенно другой механизм. Вот такая получается карусель.

**Comment by alexandra-gsoftware** [comment]
Эта проблема связана с тем, что некоторые счета в новом плане счетов "поменялись местами". Нам нужно поправить скрипты формирования эталона. На существующих же базах это сообщение появится один раз при первом обновлении плана счетов. Счета, которые поменялись местами, здесь: https://github.com/GoldenSoftwareLtd/gedemin/issues/3558#issuecomment-124501588

**Comment by NikolayUkleyko** [comment]
Я тоже заметил, что при первой установке ПИ Бухгалтерские счета программа отобразит окна с подобными сообщениями. При последующей установке ПИ Бухгалтерские счета никаких окон с сообщениями программа отображать не будет.

**Comment by NikolayUkleyko** [comment]
Данный вопрос решен. Если, нет ни у кого нет вопросов, закрывайте тему.
