### ISSUE TITLE
Поле кол-во в книге покупок

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin-apps#38]
На базе книги покупок можно сделать книгу продаж, но в ней нужен вес.
Предлагаю в таблице позиции книги покупок добавить поле вес, и добавить в процедуре формирования кол-во (пусть берется из ac_quantity)

**Comment by NikolayUkleyko** [comment]
Вес можно брать из количественных показателей в бухгалтерских проводках.
  По хорошему не мешало бы сделать еще и отдельный документ Книга продаж на базе Книги покупок образца 2015 г. К нему прикрутить свои отчеты.

**Comment by alexandra-gsoftware** [comment]
добавила
