### ISSUE TITLE
Бухгалтерия. Доработки отчета 'Функции с использованием счета/субсчета'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#40]
Исследователь > Бухгалтерия > План счетов > Функции с использованием счета/субсчета.
  Данный отчет отображает по счету связь с функциями (типовые проводки), в которых он используется.
  Пожалуйста, предусмотрите в данном отчете следующее:
1. В колонке Типовая операция сейчас входимость типовой хоз. операции отображется задом наперед. Не удобно воспринимать информацию. Сделайте, так, чтобы входимость отображалась прямо как есть.
2. В колонке Типовая проводка предусмотреть переход к типовой проводке. То есть, не в конструктор функций типовой проводки, а именно к списку типовых проводок.

**Comment by MBurakina** [comment]
Обновляй ПИ "Общие данные бухгалтерии"

**Comment by NikolayUkleyko** [comment]
Проверил.
  Хорошо.
  Если, удастся реализовать переход из отчета на список типовых проводок - будет отлично.
  Спасибо, Марина !

**Comment by MBurakina** [comment]
Коля, переход на список типовых проводок был уже вчера после обеда. Но забери опять ПИ - я в шаблоне кое-что правила.

**Comment by NikolayUkleyko** [comment]
Обновил ПИ 'Общие данные бухгалтерии'. Возможность перехода к списку типовых проводок не обнаружил.

**Comment by MBurakina** [comment]
Двойной клик по типовой проводке не работает?

**Comment by NikolayUkleyko** [comment]
Обновил ПИ - двойной клик не работает.

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Браво !

**Comment by NikolayUkleyko** [comment]
Выявлено следующее.
  При попытке перехода из отчета на автоматическую хоз. операцию появляется окно с сообщением об ошибке. Например, можно посмотреть счет 90.02, который используется в АХО '01. Формирование реализации Торговля'.
  Пожалуйста, устраните.

![1](https://cloud.githubusercontent.com/assets/11497453/9463044/9076d984-4b22-11e5-94c5-7b7b9db44fda.png)

**Comment by MBurakina** [comment]
У ТО "Реализация" к которой относится ТП "01. Формирование реализации Торговля" не проставлена компания. Отсюда и ошибка, теперь в таких случаях просто не будет открываться форма просмотра списка просмотра ТО.

**Comment by NikolayUkleyko** [comment]
Посмотрел.
  Можно ли сделать, чтобы даже при не выбранной организации был переход к списку АХО ?

**Comment by MIchaelShoihet** [comment]
Тем более что организация это поле которое практически ни когда не заполняется в ТО. Это те редкие случаи когда в Гедемине ведут несколько организаций, и ТО хотят ограничить только одной их них

**Comment by MBurakina** [comment]
Ага, разобралась. Это была автоматическая ТО. Теперь и они открываются верно. 
Обновление в ПИ "Общие данные бухгалтерии".

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Большое спасибо !

  :+1: :+1: :+1:
