### ISSUE TITLE
Бухгалтерия. Доработка отчета 'Отчет по справочнику показателей'

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#41]
Исследователь > Бухгалтерия > Отчеты бухгалтерии > Справочник показателей > Отчет по справочнику показателей.
  Сейчас по разделу с вложенными подразделами отчет отображает данные хаотично. Пожалуйста, предусмотрите, чтобы в отчете данные отображались сгруппировано по группам. То есть, чтобы отображалась сперва группа, а потом входящие в нее подгруппы, потом следующая группа и ее подгруппы и т. д.

**Comment by MBurakina** [comment]
Обновляй ПИ "Показатели"

**Comment by NikolayUkleyko** [comment]
Проверил.
  Есть вопросы.
  1. Показатели не отображаются в той же последовательности, как они отображаются в справочнике показателей. Необходимо учесть важный момент, когда одна часть показателей входит в головную ветку, а другая часть показателей входит в другую подветку. В параметрах отчета выбрана одна ветка 'Раздел I'. На примере, Долгосрочные активы > Раздел I > Ветка 130.
  2. В параметрах отчета при выборе нескольких веток 'Раздел I' и 'Раздел II' по-прежнему показатели выводятся не в оригинальной последовательности, как в справочнике показателей. При этом в заголовке отчета присутствуют повторяющие наименования веток. Такого быть не должно.
  В результате необходимо получить отчет по любому разделу/разделам с оригинальным отображением показателей любой входимости.
  Этот отчет очень удобен при работе в конструкторе с функцией расчета отчетов бухгалтерии. Открыта функция и подсматриваем в отчет, сохраненный в PDF (перечень показателей с соответствующими RUID).
![1](https://cloud.githubusercontent.com/assets/11497453/9178200/ac8a667a-3f9e-11e5-95c5-b77961380f55.png)
![2](https://cloud.githubusercontent.com/assets/11497453/9178201/acae0cec-3f9e-11e5-8886-e8ec2cd9c64c.png)
![3](https://cloud.githubusercontent.com/assets/11497453/9178204/b1111bda-3f9e-11e5-8469-90cd2f7d5bc8.png)
![4](https://cloud.githubusercontent.com/assets/11497453/9178206/b2cb1a3e-3f9e-11e5-96f3-a322709157d3.png)
![5](https://cloud.githubusercontent.com/assets/11497453/9178207/b45e23be-3f9e-11e5-8c1e-32badf404430.png)

**Comment by NikolayUkleyko** [comment]
Дополнительно к вышеизложенному:
  3. В отчете не выводятся RUID по головным веткам. Надо, чтобы выводились по всем веткам.
  4. В одной ветке выводятся одинаковые RUID.
  Пожалуйста, поправьте.

**Comment by olga-hozyanin** [comment]
С уважением,

Хозянин Ольга


11 августа 2015 г., 20:27 пользователь NikolayUkleyko <
notifications@github.com> написал:

**Comment by MBurakina** [comment]
OK

**Comment by MBurakina** [comment]
Я поправила и РУИДЫ, и доработала отчет так:
добавлены параметры "Детально" и "Дата". Дата имеет смысл только если стоит галка детально. 
Галка детально говорит о том, что помимо показателей в отчете будут отображены связанные с ними "Показатели на дату"(поля дата, план счетов и функция расчета)  и "Составляющие показателя"(тип показателя, дебит-счет, дебит-аналитика, кредит-счет, кредит-аналитика). 
Посмотри так ли все как ты хотел.

**Comment by NikolayUkleyko** [comment]
Проверил.
  Есть вопросы:
1. Можно ли убрать параметр "Детально" ? Сейчас достаточно заполнить параметр "На дату" и отчет сформируется с детальными данными. Если, поле параметр "На дату" не заполнять, то отчет будет сформирован без детальных данных.
2. При вводе в параметр "На дату" даты 01.01.2014 в отчет попадают детальные данные за предыдущие периоды 01.01.2004. Необходимо, чтобы в данном случае попадали детальные данные >= указанной даты.
3. Необходимо, чтобы перечень аналитик (более одной) отображался с новой строки. Сейчас перечень аналитик и их значения отображаются подряд.

**Comment by MBurakina** [comment]
1. Сейчас достаточно заполнить параметр "На дату" и отчет сформируется с детальными данными.
Нет, это не так, с подробностями или нет сейчас зависит  от галочки. Но да, я могу ее убрать и все завязать на дату.

2. При вводе в параметр "На дату" даты 01.01.2014 в отчет попадают детальные данные за предыдущие периоды 01.01.2004. 
Значит более поздних показателей нет.  Смысл показателя на дату - актуальное значение не текущее, а на заданное число. И не может быть дата ввода показателя больше.
например у показателя две детали. Деталь1 на 01.01.2004, Деталь2 на 01.01.2015
В отчете на дату 31.12.2014 будет показатель за 01.01.2004, т.к. Деталь2 еще не применима.

3. Не обещаю, но попробую.

**Comment by NikolayUkleyko** [comment]
- С параметром "На дату" порядок.
- Перечень аналитик и их значений отображается с новой строки. Порядок.
- Можно ли предусмотреть возможность отображения входимости составляющей показателя с типом "P" (показатель) ?
![6](https://cloud.githubusercontent.com/assets/11497453/9500784/f0aac8ac-4c2f-11e5-8dbb-ad70a61b8c04.png)

**Comment by MBurakina** [comment]
Ничего не поняла. Перефразируй, пожалуйста.

**Comment by NikolayUkleyko** [comment]
В отчете, где встречается составляющая показателя с типом "P" (показатель) необходимо отображать полный путь ссылаемого показателя. В данном случае будет так:
##### Налоги > Баланс > Ф № 1. Бухгалтерский баланс > I. Долгосрочные активы > 130 > 131.

**Comment by MBurakina** [comment]
Добавила вывод всего пути вместо имени для групп.
И дополнительно для показателя. 
Удалила в шапке разметку под колонки - все равно она не соблюдается из-за отступов.
Немного подправила шаблон - читабельность выросла.
Обновления в ПИ "Показатели".

**Comment by NikolayUkleyko** [comment]
Проверил.
  Есть вопросы:
1. Есть один показатель на дату и один счет по составляющей показателя (тип показателя "Сальдо на начало"). В отчете не надо отображать вторую строку "Показатель". Здесь же составляющей показателя с типом "Показатель" нет.
![8](https://cloud.githubusercontent.com/assets/11497453/9525389/99dd0a68-4cec-11e5-8955-4f1c2b046e09.png)
2. В отчете составляющие показателя с типом "Показатель" отображаются не верно. Как-будто они сами на себя ссылаются. Вся прелесть данного отчета, что он наглядно отображает, что такая-то составляющего показателя ссылается на такой-то показатель.
![9](https://cloud.githubusercontent.com/assets/11497453/9525503/142144ec-4ced-11e5-9132-73488b4ac36f.png)
На самом деле здесь вот такие составляющие показателя (приведу не все):
![10](https://cloud.githubusercontent.com/assets/11497453/9525574/6892c9a6-4ced-11e5-8652-2acf8d422dee.png)
![11](https://cloud.githubusercontent.com/assets/11497453/9525575/6959599a-4ced-11e5-9a17-1680d690ac22.png)
3. Можно ли предусмотреть возможность перехода из отчета непосредственно на составляющие показателя ? Так будет очень удобно и оперативно править выявленные ошибки.

**Comment by MBurakina** [comment]
1. У меня нет твоей базы и я не могу проверить твои слова. Но есть предположение. И скорее всего я это починила. 

2. Всей прелести изначально в этом отчете не было. Почему ты пишешь так, будто я что-то у отчета отломала? done

3. done

4. Можно ли сразу писать все пожелания по отчету, ты же не от клиентов их получаешь. Как ты хочешь открывать: дерево или сразу составляющий на редактирование?

И традиционно все лежит в ПИ "Показатели".

**Comment by NikolayUkleyko** [comment]
>Можно ли сразу писать все пожелания по отчету, ты же не от клиентов их получаешь. Как ты хочешь открывать: дерево или сразу составляющий на редактирование?

  Я плотно работаю с отчетами бухгалтерии и по ходу возникают предложения. Открывать необходимо только составляющую показателя.

**Comment by NikolayUkleyko** [comment]
Проверил.
  Пункты 1, 2, 3 решены.
  Остался пункт 4. Лучше предусмотреть возможность открытия из отчета не окна редактирования показателя, а перечень составляющих показателя. Потом можно будет добавить/изменить/удалить запись.

**Comment by MBurakina** [comment]
done

**Comment by NikolayUkleyko** [comment]
Проверил.
  Пункт 4 - :+1:.   
  Выявлено следующее.
  В отчете каждая составляющая показателя на одну дату каждый раз выводится с отображением показателя на дату. Пожалуйста, сгруппируйте составляющие показателя по каждому показателю на дату.
![14](https://cloud.githubusercontent.com/assets/11497453/9548461/4db8260a-4da9-11e5-94e0-4dc9729bdd9f.png)
  По данному примеру вверху будет один раз указано: 01.01.2014 План счетов.

**Comment by MBurakina** [comment]
+

**Comment by NikolayUkleyko** [comment]
Проверил.
  Работает корректно.
  Большое спасибо !
  :+1: :+1: :+1: :+1: :+1:
