### ISSUE TITLE
Бухгалтерия. Справочник показателей. Доработать макросы сохранения объектов в настройку

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#43]
Исследователь > Бухгалтерия > Отчеты бухгалтерии > Справочник показателей > Макросы > Добавить значения показателей в настройку, Добавить показатели в настройку.
  Пожалуйста, предусмотрите возможность сохранения объектов не только в настройки, но и в ПИ.

**Comment by MBurakina** [comment]
Коля, в стандартной комплексной автоматизации нет такого макроса. Он где-то отдельно лежит? 
Если ты про контекстное меню, то щелчок по пункту "Добавить в настройку..." вызывает форму добавления именно в ПИ. Для добавления в настройки нужно зажать Shift и щелкнуть по пункту "Добавить в настройку...".

**Comment by MIchaelShoihet** [comment]
Есть настройка называется добавление показателей служебная. В ней содержаться эти макросы.

**Comment by MBurakina** [comment]
В ПИ "Показатели" лежат оба макроса.
Добавляют тихо, без зависимых. 
Если такой объект уже есть в ПИ - пропускают.

**Comment by NikolayUkleyko** [comment]
Макросы добавлены.
  Продолжены работы по их доработке в другой теме.
