### ISSUE TITLE
Создание нового документа vs наследование

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin-apps#45]
Есть тип документа Д. У него есть наследник Д1 (те же таблицы, но, ес-нно, другой документтайп). При нажатии на кнопочку Добавить в форме просмотра документа Д вылазит форма выбора: добавить Д или Д1. Для документов это не нужно! (Либо дайте возможность это отключать)

**Comment by NikolayUkleyko** [comment]
Конечно, на практике это должно регулироваться.

**Comment by alexandra-gsoftware** [comment]
Еще почему-то гриды не наследуются у Д1 (можно было бы их копировать, как формы)

**Comment by alexandra-gsoftware** [comment]
и отображать в форме просмотра Д документы типа Д1 тоже не нужно (либо дать возможность регулировать это)

**Comment by alexandra-gsoftware** [comment]
также поступила просьба дать возможность регулировать это у справочников...

**Comment by gsbelarus** [comment]
Это относится к проекту gedemin, а не gedemin-apps.

**Comment by alexandra-gsoftware** [comment]
переносим в другой проект
