### ISSUE TITLE
Etalon business. Торговля. Исправить/создать/скрыть отчеты

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#47]
Исследователь > Торговля.
  Пожалуйста, исправьте следующие отчеты:
  1. Документ "03. Отпуск товара на сторону (оптовая торговля)" > Отчет "Реестр отпусков по документам" - ошибка.
  2. Отчеты по торговому складу > Отчет "Товарно-денежный отчет по группам ТМЦ" - ошибка.

**Comment by MBurakina** [comment]
п 1 поправила, обнови ПИ "Торговля-отчеты"
п 2 - напиши с какими параметрами там ошибка, не могу повторить.

**Comment by NikolayUkleyko** [comment]
Момент...
![1](https://cloud.githubusercontent.com/assets/11497453/9325061/7277cbee-4598-11e5-9523-aa5163210e25.png)

**Comment by MBurakina** [comment]
Коля, мне нужна база на которой возникает такая ошибка. Понимаешь?

**Comment by NikolayUkleyko** [comment]
Хорошо.
  Не сейчас.
  Позже.

**Comment by NikolayUkleyko** [comment]
Проверено.
  1-й отчет по-прежнему с ошибкой.
![2](https://cloud.githubusercontent.com/assets/11497453/9334355/1d5eb69c-45d7-11e5-8b68-0e8accb27876.png)

**Comment by MBurakina** [comment]
Обнови ПИ, я не шутила про потертые изменения вечером.

**Comment by NikolayUkleyko** [comment]
Проверил.
  Отчет № 1 работает корректно.
  Спасибо !
  Тему не закрываю, так как могут всплыть другие отчеты со своими проблемами.

**Comment by NikolayUkleyko** [comment]
По отчету № 2 могу только скинуть фрагмент кода, к которому переходим при нажатии на кнопку "Редактировать".
![3](https://cloud.githubusercontent.com/assets/11497453/9350669/5942c886-465b-11e5-93f8-289c5e9a5f8e.png)

**Comment by MBurakina** [comment]
По п.2 в любом случае надо смотреть на конкретном примере. Скинь базу архивом на почту или через гугл-диск.

**Comment by NikolayUkleyko** [comment]
Исследователь > Торговля > Валютная торговля.
  Пожалуйста создайте реестры операций за период для следующих документов:
1. 03. Отпуск товара на экспорт (оптовая торговля).
2. 05. Возврат товара от экспортного покупателя.
3. 07. Возврат поставщику импортного товара.
4. 08. Сведения об уплате косвенных налогов.

**Comment by MBurakina** [comment]
Коля, распиши, пожалуйста, структуру каждого отчета.

**Comment by NikolayUkleyko** [comment]
Можно посмотреть существующие реестры по аналогичным рублевым документам:
1. 03. Отпуск товара на сторону (оптовая торговля) <> 03. Отпуск товара на экспорт (оптовая торговля).
2. 05. Возврат товара от покупателей <> 05. Возврат товара от экспортного покупателя.
3. 07. Возврат товаров поставщику <> 07. Возврат поставщику импортного товара.
4. По документу "08. Сведения об уплате косвенных налогов" произвольная структура реестра.

**Comment by MBurakina** [comment]
У этих документов есть существенное различие - одни в рублях, другие в валюте. Это порождает дополнительные колонки типа курса, курсовой разницы, даты, цены в эквиваленте. 
По этому еще раз вопрос: что нужно включать в реестр по валютным документам?

**Comment by alexandra-gsoftware** [comment]
Для каждого реестра нужен список входящих параметров и колонок, чтобы потом не пришлось переделывать.

**Comment by NikolayUkleyko** [comment]
Хорошо.
  Позже напишу, что к чему.

**Comment by NikolayUkleyko** [comment]
Реестры и отчеты по валютным документам будут идентичны реестрам и отчетам по рублевым документам. Все отличие будет сводится к следующему:
- вместо рублевой цены, суммы без НДС, суммы НДС, суммы с НДС необходимо выводить валютные;
- добавить параметр "Валюта" (необязательный, если не выбран, то все валюты);
- группировать по валюте.

>Это порождает дополнительные колонки типа курса, курсовой разницы, даты, цены в эквиваленте. 

  Это выводить не надо.

**Comment by MBurakina** [comment]
done

**Comment by NikolayUkleyko** [comment]
Проверил.
  Есть вопросы:
1. "03. Отпуск товара на экспорт (оптовая торговля)" > реестр. В колонке "Сумма в прих. ценах" необходимо из приходной накладной брать: Контрактная цена (вал.) x Количество.
2. "05. Возврат товара от экспортного покупателя" > реестр. Отсутствует шаблон.
3. "07. Возврат поставщику импортного товара" > реестр. В колонках следует выводить значения так:

- "Сумма в прих. ценах" необходимо из приходной накладной брать: Контрактная цена (вал.) x Количество;
- "Сумма НДС" в приходной импортной накладной НДС обычно не указывается;
- "Сумма с НДС" = "Сумма в прих. ценах" + "Сумма НДС".

  В шаблонах вышеуказанных реестров должна быть верхняя группировка по каждой из валют.

4. "08. Сведения об уплате косвенных налогов". Необходимо создать реестр по шапке и позиции документа. При этом по каждому документу выводить итоги по колонкам:

- количество;
- стоимость товара (работы);
- налоговая база НДС.

**Comment by MBurakina** [comment]
1. ok
2. ok
3. заголовок ok, Сумма в приходных ценах ok, сумма НДС и Сумма с НДС не понятно что ты хотел сказать. 

Во всех шаблонах была группировка по валюте. 

по 08.Сведения об уплате косвенных налогов непонятно какие параметры входящие, 
какие колонки нужны в реестре из шапки, из позиции. 
Что такое "налоговая база ндс" и откуда она берется. 
Итоги по этим трем колонка по каждой накладной(по сути позиции в документе 08.Сведения об уплате косвенных налогов) или по каждой шапке д-та 08.Сведения об уплате косвенных налогов?

**Comment by NikolayUkleyko** [comment]
>3. заголовок ok, Сумма в приходных ценах ok, сумма НДС и Сумма с НДС не понятно что ты хотел сказать.

  По импорту нет НДС и соответственно нет суммы НДС. Поэтому, сумма с НДС будет равна сумме без НДС.

>Во всех шаблонах была группировка по валюте.

  Я имею в виду, чтобы в самом шаблоне отдельно выводились данные по одной валюте (с указанием валюты), потом по другой и т. д.

>по 08.Сведения об уплате косвенных налогов непонятно какие параметры входящие, 
какие колонки нужны в реестре из шапки, из позиции. 
Что такое "налоговая база ндс" и откуда она берется. 
Итоги по этим трем колонка по каждой накладной(по сути позиции в документе 08.Сведения об уплате косвенных налогов) или по каждой шапке д-та 08.Сведения об уплате косвенных налогов?

Входящие параметры:
- Период;
- Поставщик (выбор из множества, если не выбран, то все).

  Колонки шапки надо взять из шапки документа (номер, дата, поставщик, договор, период, причина возникновения). Колонки позиции необходимо взять из позиции документа (номер ТТН, дата ТТН) + из отчета "Сведения об уплате косвенных налогов" взять итоговые колонки.

**Comment by MBurakina** [comment]
В шаблоне есть группировка по валюте с выводом на просмотр/печать валюты, ее кода и итогами.
валюта 1, код валюты1
    дата номер суммы
    ........
    дата номер суммы
итого по валюте1
валюта 2, код валюты 2
    дата номер суммы
    .........
    дата номер суммы
итого по валюта2
итого по отчету

**Comment by NikolayUkleyko** [comment]
Хорошо.
  Потом посмотрю.

**Comment by MBurakina** [comment]
" из отчета "Сведения об уплате косвенных налогов" взять итоговые колонки."
Там нет итоговых колонок, есть только подсчет сумм по колонкам:
  Количество товара
  Стоимость товара (работы) 
  Налоговая база НДС
  Суммы налогов НДС

Ты про них?
Итоги выводить по шапке или по клиету?

**Comment by MBurakina** [comment]
ПИ GS. Торговля. Уплата косвенных налогов

**Comment by NikolayUkleyko** [comment]
По следующим документам в шаблонах есть группировка по валюте, а в сформированных отчетах нет:
1. "03. Отпуск товара на экспорт (оптовая торговля)".
2. "05. Возврат товара от экспортного покупателя".
3. "07. Возврат поставщику импортного товара".

**Comment by MBurakina** [comment]
Поправила. это в торговля-отчеты

**Comment by NikolayUkleyko** [comment]
Если, в параметрах отчета выбрана валюта, то в заголовке отчета не отображается. В шаблоне отчета все указано.

**Comment by MBurakina** [comment]
done

**Comment by NikolayUkleyko** [comment]
Марина, мои правки ты не затерла.
  По-прежнему в заголовках отчетов не отображается валюта.

**Comment by MBurakina** [comment]
значит у тебя не обновилось пи.
Коля, а какой у тебя ехе?

**Comment by MBurakina** [comment]
Все, ничего не надо, Александра закинула.

**Comment by NikolayUkleyko** [comment]
Марина, пожалуйста, посмотри. В реестре по документу "05. Возврат товара от экспортного покупателя" нет сумм в итоговых строках.

**Comment by MBurakina** [comment]
Посмотрела.

**Comment by NikolayUkleyko** [comment]
Почему-то поменялась версия файла ПИ "Торговля - Отчеты" с 1.0.0.137 на 1.0.0.135 ? Соответственно все опять затерлось. Жаль. :unamused:

**Comment by MBurakina** [comment]
Передавай свои приветы Жанне. 
В понедельник поправим.

**Comment by NikolayUkleyko** [comment]
Устранена ошибка по "Товарно-денежный отчет по группам ТМЦ".
  Пока закроем тему.
