### ISSUE TITLE
Не грузится комплексная автоматизация

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#49]
Стандартные объекты, те у которых ИД меньше 147000000, грузятся на БД скриптами и МЕНЯТЬСЯ должны только в модифае. Изменение их через ПИ может привести к тому, что перестанет ПИ грузится. Что сейчас и произошло с планом счетов.

Мне надо полный список того, что поменялось в СТАНДАРТНЫХ счетах, т.е. тех, у которых ИД меньше 147000000 и которые всю жизнь поставлялись с БД.

Включая: удаление таких счетов, переименование, добавление и т.п.

На основании этого списка я сделаю модифай процедуру.

**Comment by NikolayUkleyko** [comment]
Карусель: ПИ<>Скрипты.
  Нельзя ли сделать проще ?
  Конечно, вести протокол всех изменений, включая, мелкие и все другие хорошо. Но ! Чересчур.
*Было                                                                       Стало*
10.12 (Амортизация МБП)                                         10.13 (Износ инвентаря и хозяйственных принадлежностей, инструментов)
10.13 (Амортизация спецодежды)                            10.14 (Износ спецодежды)

90.02 (Себестоимость реализации)                          90.04 (Себестоимость реализованной продукции, товаров, работ, услуг)
90.03 (Налог на добавленную стоимость)                90.02 (Налог на добавленную стоимость, исчисляемый из выручки от реализации продукции,
товаров, работ, услуг)
90.05 (Прочие налоги и сборы из выручки)               90.03 (Прочие налоги и сборы, исчисляемые из выручки от реализации продукции, товаров, работ, услуг)

91.02 (Операционные расходы)                                91.04 (Прочие расходы)
91.03 (Налог на добавленную стоимость)                91.02 (Налог на добавленную стоимость)
91.09 (Сальдо операционных доходов и расходов) 91.05 (Сальдо прочих доходов
и расходов)

  Постарался вспомнить. Быть может, я что-то не указал.

**Comment by alexandra-gsoftware** [comment]
1)в этих счетах настраиваются аналитики через пи, поэтому без пи не обойтись
2) висит же в багбейзе вопрос про изменение скриптов формирования их на эталоне

**Comment by NikolayUkleyko** [comment]
Да, Александра на 1000 % права.
  План счетов сделал.
  Аналитики хранятся в ПИ. Может, мне еще написать, какие по счетам аналитики были и какие стали ? Это не возможно.
  План счетов и бухгалтерский потенциал программы это одно из основного функционала программы. Я же с Александрой не решу такие вопросы.

**Comment by alexandra-gsoftware** [comment]
https://github.com/GoldenSoftwareLtd/gedemin-apps/issues/37

**Comment by gsbelarus** [comment]
Срочно подскажите что делать:

1) из эталона убрать план счетов полностью
2) оставить план счетов, но с правками, которые сделал николай.

Кроме этого, я сделаю так, что при загрузке ПИ, если в БД уже есть
счет с таким же наименованием, но с другим РУИДом, то существующий
в БД счет тихонько переименуется. Например, было 90.04 станет *90.04.
Дальше пусть пользователь думает, что с этим делать.

Вопрос к знатокам: у нас как проводки привязаны при формировании их
через ТП, по ИД или по номеру счета? если по ИД, то все будет работать
и после переименования счета.

**Comment by gsbelarus** [comment]
@MIchaelShoihet @stasgm @yoannawx

**Comment by yoannawx** [comment]
я за вариант 1) из эталона убрать план счетов полностью,
раз есть отдельное пи, которое проще поддерживать в актуальном состоянии

С уважением,
Жанна Хилько,
специалист по внедрению и сопровождению
8-029-376-13-43
icq 342682323

2015-08-19 12:22 GMT+03:00 Andrej Kirejeŭ <notifications@github.com>:

**Comment by MIchaelShoihet** [comment]
Да из эталона надо убирать счета. И план счетов делать полностью в настройке. Проблема будет у старых клиентов, но им обновление делать только в исключительных случаях. Проводки формируются по ИД (РУИД).

**Comment by gsbelarus** [comment]
Если я сейчас уберу, то что будет после загрузки КА? Там уже есть весь план счетов?

**Comment by NikolayUkleyko** [comment]
Из эталона убрать план счетов. Я до недавнего момента предполагал, что его там нет. Все в ПИ.
  Может, я не и такой большой знаток, предполагаю, что формируемые бухгалтерские проводки привязаны к типовым проводкам по ID.
  По поводу обновления плана счетов у старых клиентов. В 99 % план счетов обновлять ни в коем случае не стоит. Так, как обще утвержденный план счетов это одно, а реальный план счетов у каждого клиента это совершенно другое. Только, если план счетов клиент не редактировал, тогда можно его обновить. Попробуйте, обновите план счетов на ВМК или на БМКК и т. д. Вам позвонят.
:+1: -

**Comment by MIchaelShoihet** [comment]
Тогда Коле надо сейчас в первую очередь сделать полностью новый план счетов. На чистой базе. И затем аккуратно поменять все настройки на новые счета.

**Comment by NikolayUkleyko** [comment]
Я предполагаю, что план счетов должен (обязан) установится первым делом, а потом макросы, типовые хоз. операции, типовые проводки, данные и другое.

**Comment by NikolayUkleyko** [comment]
Знаете, я не робот, чтобы по 100 раз делать одно и тоже.

**Comment by MIchaelShoihet** [comment]
План счетов можно попробовать сделать автоматически. Но настройки типовых проводок и расчеты необходимо будет поменять.

**Comment by gsbelarus** [comment]
А что если апдейтом переименовать счета, как коля предлагает в начале этого issue?

**Comment by MIchaelShoihet** [comment]
Т.е. ничего не менять, просто написать UPDATE в exe который переименует счета. Но в ПИ нам все равно нужны данные записи, они хранят назначенные для них аналитики

**Comment by MIchaelShoihet** [comment]
В таблице ac_account можно оставить разделы и саму запись план счетов

**Comment by gsbelarus** [comment]
Все остальное останется. Ид не изменится. просто переименуются. Это пойдет? Например, после апгрейда 91.09 превратится в 91.05.

**Comment by MIchaelShoihet** [comment]
А ПИ не грузятся только потому что номера счетов поменялись или в принципе нельзя в ПИ добавлять записи с ID < 14700000. Потому что если второе, то счета в ПИ сохранять все равно надо на эталоне нет аналитик....

**Comment by gsbelarus** [comment]
ПИ не грузится, потому что при загрузке уже находит счет с таким номером, но другим ИД.

**Comment by gsbelarus** [comment]
Если на существующих базах (Береза, бро и т.п.) переименуются некоторые счета, как Николай написал выше, это будет проблема или нет?

**Comment by MIchaelShoihet** [comment]
В том то и дело что на существующих базах чаще всего ничего менять не надо. И ПИ мы можем это как-то контролировать, т.е. на существующие базы с настроенным учетом не грузить ПИ с проводками и счетами...

**Comment by alexandra-gsoftware** [comment]
на эталоне нужно просто переименовать 2 (два) счета, и все будет как раньше, прекрасно. Имена этих счетов здесь уже фигурировали....

**Comment by gsbelarus** [comment]
Почему 2? В списке Коли их больше.

**Comment by alexandra-gsoftware** [comment]
потому что на двух счетах вылазит сообщение при загрузке

**Comment by alexandra-gsoftware** [comment]
хотя отбой. я придумала как решить без скриптов. сейчас поправим, и будем делать полностью новый...

**Comment by gsbelarus** [comment]
В скриптах все равно надо править. Это раз. Совсем новый это как? Нежелательно чтобы у существующих клиентов задвоились ВСЕ счета. 

Давайте то что есть в эталоне оставим и будем использовать. Добавлять только новые счета уже через ПИ.

И может быть, было ошибкой переименовывать счета. Надо было отключить, те которые уже не используются и создать новые, как надо.

**Comment by gsbelarus** [comment]
На будущее, сама операция переименования чего-то (т.е. создания фактически нового объекта), но со старым РУИДом -- дорога в ад. Не нужен старый объект -- удаляем или отключаем. нужен новый -- создаем. Это правильный путь.

**Comment by gsbelarus** [comment]
Сейчас же мы забрались в задницу из которой без потерь трудно вылезти.

**Comment by MIchaelShoihet** [comment]
Вообще разговор был сделать так как нам удобней. И значит надо так и сделать. Завести новые счета, а старые отключить. Мне кажется еще не поздно.

**Comment by gsbelarus** [comment]
До завтра таймаут. Я подумаю как сделать с минимальными последствиями.

Александра, список, который у вас на бумажке, так вот, его нет в списке счетов выше. МНЕ НУЖЕН ПОЛНЫЙ СПИСОК ЧТО НА ЧТО МЕНЯЕТСЯ.

**Comment by alexandra-gsoftware** [comment]
отправила список на почту

**Comment by alexandra-gsoftware** [comment]
итак, чтобы сейчас грузилась комплексная автоматизация, нужно поменять в скриптах формирования эталона следующие счета:
91.02 -> 91.04
91.03 -> 91.02
91.04 -> 91.03

**Comment by YRozmysl** [comment]
Не загружается на чистую базу ПИ Бухгалтерские счета, ошибка 
10:21:56  Изменен объект: 90.01 (Субсчет)
[Ошибка] 10:21:56  Объект не найден: 147087049_418894751 План счетов\Неиспользуемые счета\_90
10:21:56  Изменяется объект: 90.04, 344604_17, ac_account
[Ошибка] 10:21:56  Поле "Родитель" ("AC_ACCOUNT"."PARENT") должно быть заполнено.

**Comment by NikolayUkleyko** [comment]
Юра, пожалуйста, уточни, что за чистая база данных: с сайта комплексная автоматизация или вовсе чистая (~ 5 Mb) ?
  Счета "_90" и "90.04" (и его родитель счет "90") присутствуют в базе данных и входит в ПИ "Бухгалтерские счета".
  Не сложно представить череду событий при следующем изменении плана счетов: ПИ себе - скрипты себе.
  Спасибо !

**Comment by gsbelarus** [comment]
Подождите пока, тут надо придумать как решить. Как бы не пойти совсем неправильным путем. потому что как пошли сейчас -- это тупик. У нас 2200 зарегистрированных клиентов только на новом экзешнике с интернет регистрацией. Отсечь их от новых проводок? Как?

**Comment by NikolayUkleyko** [comment]
Учтите следующее.
  Вариант, предложенный Михаилом Юрьевичем: "Тогда Коле надо сейчас в первую очередь сделать полностью новый план счетов. На чистой базе. И затем аккуратно поменять все настройки на новые счета... Но настройки типовых проводок и расчеты необходимо будет поменять." может привести к тому, что просто обновить проводки или отчеты бухгалтерии не получится. Потому, что, например, есть счет Счет "60 - Расчеты с поставщиками и подрядчиками	" с RUID 366000_17, то заново созданный этот же счет будет с RUID 147107218_418894751. И получится, что на клиентской базе данных придется перебивать ОГРОМНОЕ множество типовых проводок, типовых документов (условия на счета) и отчеты бухгалтерии. В конструкторе функций в блоке в поле "Счет" видим "60", но реально это не "60". Допускается % опечаток . То есть,  на данный момент весь бухгалтерский механизм работает корректно и надежно. Что будет после - трудно представить.
:+1:

**Comment by NikolayUkleyko** [comment]
Не стоит на скаку решать данный вопрос. Здесь необходимо спокойно и рассудительно все взвесить.
  Выход будет найден.
:100:

**Comment by MIchaelShoihet** [comment]
По плану счетов, делаем следующее:
Все счета которые поменяли свое назначение переименовываем в счет с "_"
и  добавляем  новый  счет.  Если  старый  счет  бы  < 147000000 то его
переименование  произойдет  в  exe,  если уже > 147000000 то меняем на
базе и добавляем в ПИ, а новый счет надо добавлять уже в ПИ.
Соответственно все расчеты и проводки должны делаться на новые счета.
Если  поменялся номер счета, и раньше такого номера счета не
было,  то  счета  до  147000000  меняем в exe (эталоне) выше 147000000
меняем в ПИ.

**Comment by gsbelarus** [comment]
Я по этому вопросу сегодня напишу развернутый план действий.

**Comment by NikolayUkleyko** [comment]
Уточните по пунктам что делать ?

**Comment by gsbelarus** [comment]
Напишу сюда

**Comment by NikolayUkleyko** [comment]
Напишите, чтобы не пришлось еще и еще переделывать.

**Comment by alexandra-gsoftware** [comment]
>>>еще и еще переделывать.

добро пожаловать в клуб(

**Comment by gsbelarus** [comment]
У нас в эталоне всегда поставлялся план счетов, на основе которого сделаны планы счетов у всех наших клиентов.

Сейчас план изменился. Изменения сведены в таблицу:

https://docs.google.com/spreadsheets/d/1CPEuIa38lKa-0RTH7lBMLWd9vMpGtj0AhxbxoOnZU4o/edit?usp=sharing

Делаем следующее:

## Номер счета и описание не изменились

Ничего не меняем. Все продолжает работать. Счет можно использовать в настройке ТП.

## Изменилось описание, но смысл остался прежним

Поменяем в скриптах эталона. Апгрейдом БД поменяем на новое описание. Все продолжает работать. Счет можно использовать в настройке ТП. 

Если счет входит в некоторые ПИ, то их надо будет пересохранить.

## Счета нет в новом плане счетов

Убираем из скриптов эталона. Апгрейдом БД проверяем: если счет задействован в проводках или его РУИД используется в скрипт-функциях, то переименовываем (добавляем подчеркивание в начало номера). Если не используется -- удаляем из БД. Проверка распространяется на сам счет и на все его субсчета.

Счет нельзя использовать для настройки ТП.

## Поменялся смысл счета

Например, было 10/08 "Строительные материалы" стало 10/08 "Временные сооружения".

Фактически это означает, что старый счет был удален, а новый, с таким же номером, но с другим описанием, создан.

В части удаления будет действовать процедура, описанная выше. Новый счет должен быть создан разработчиком (т.е. его не будет в скриптах эталона) и должен грузиться на базу данных через пространство имен. РУИД нового счета уже будет не системным (ИД меньше 147 000 000), а обычным.

Теперь важный момент, если разработчик просто переименовал 10/08 из "Строительные материалы" во "Временные сооружения", то у счета остался старый РУИД. Т.е. для системы он по-прежнему счет "Строительные материалы".

Что надо сделать:

1. Апгрейдить БД (апгрейд еще не готов! я напишу сюда когда сделаю) или вручную переименовать старый счет в "_10.08".
2. Создать новый счет, с новым описанием и новым РУИД-ом. Включить его в ПИ плана счетов.
3. Пройтись по всем ТП и заменить в блоках проводок старый счет на новый.
4. Пересохранить все ПИ с измененными ТП.

Подсказка: приведенный ниже запрос, позволяет найти ТО, в которых задействован счет.

```
select t.*
from
  ac_trrecord t join gd_function f
    on f.id = t.functionkey
where
  f.script like '%147024624_95648234%'
```

Между знаками процента надо вписать РУИД старого счета.

Исправив все ТП, можно в редакторе скрипт-объектов задать поиск по всей базе данных и ввести РУИД старого счета -- найдутся все скрипт-функции, где использовался старый счет.

**Comment by NikolayUkleyko** [comment]
Возникли вопросы:
> ### 1. Изменилось описание, но смысл остался прежним

>Поменяем в скриптах эталона. Апгрейдом БД поменяем на новое описание. Все продолжает работать. Счет можно использовать в настройке ТП.

>Если счет входит в некоторые ПИ, то их надо будет пересохранить.

#####  Зачем, счета, входящие в некоторые ПИ, пересохранять ? Ведь в типовых проводках счета идентифицируются по RUID, а не по наименованию.

> ### 2. Счета нет в новом плане счетов

>Убираем из скриптов эталона. Апгрейдом БД проверяем: если счет задействован в проводках или его РУИД используется в скрипт-функциях, то переименовываем (добавляем подчеркивание в начало номера). Если не используется -- удаляем из БД. Проверка распространяется на сам счет и на все его субсчета.

>Счет нельзя использовать для настройки ТП.

#####  Сейчас в бухгалтерских проводках вместо 92-х счетов используются 91-е счета. Есть клиенты, которые работают с не полностью обновленным планом счетов. То есть, они помимо части новых счетов, продолжают использовать старые счета (92-е). При этом они привыкли и довольны. Получают необходимые данные. В идеале у всех клиентов необходимо актуализировать план счетов и перенастроить все типовые проводки и прочее. В реалии такого нет. Что же будет, когда exe выполнит modify плана счетов ? Будет множество вопросов и проблем: "Где 92-е счета ?". Через modify в exe удалять не используемые счета не есть хорошо. Так как, в план счетов можно добавлять свои счета. Это для себя решает бухгалтер. В итоге также будут вопросы: "Куда счета ?".

> ### 3. Поменялся смысл счета
>...
>Что надо сделать:

>Апгрейдить БД (апгрейд еще не готов! я напишу сюда когда сделаю) или вручную >переименовать старый счет в "_10.08".
>Создать новый счет, с новым описанием и новым РУИД-ом. Включить его в ПИ плана счетов.
>Пройтись по всем ТП и заменить в блоках проводок старый счет на новый.
>Пересохранить все ПИ с измененными ТП.
>Подсказка: приведенный ниже запрос, позволяет найти ТО, в которых задействован счет.

```javascript
select t.*
from
  ac_trrecord t join gd_function f
    on f.id = t.functionkey
where
  f.script like '%555_777%'
```
>Между знаками процента надо вписать РУИД старого счета.

#####  По поводу SQL-запроса не согласен. Например, посмотрите счет 90.01 (Выручка от реализации продукции, товаров, работ, услуг). SQL-запрос ничего не покажет. На самом деле данный счет много, где используется. Есть проработанный верный SQL-запрос:

```javascript
select 
  F.ID 
, F.NAME 
, F.MODULE 
, TR.DESCRIPTION 
, coalesce(T.ID, coalesce(RL.REPORTGROUPKEY, coalesce(oe.OBJECTKEY, F.MODULECODE)))  as GROUP_ID 
, coalesce(TR.ID, coalesce(RL.ID, coalesce(oe.ID, F.ID))) as Element_ID 
, 
  (select 
     cast(list(NAME, ' -> ') as varchar(1024)) as NAMEL 
   from 
     (select 
        cast(list(P.NAME, ' -> ') as varchar(1024)) as NAME 
      from 
        AC_TRANSACTION P 
      where 
        P.LB <= T.LB 
        and P.RB >= T.RB 
      group by 
        P.LB 
      order by 
        P.LB asc)) as LISTT 
from 
  GD_FUNCTION F 
  left join AC_TRRECORD TR on TR.FUNCTIONKEY = F.ID 
  left join AC_TRANSACTION T on T.ID = TR.TRANSACTIONKEY 
  left join RP_REPORTLIST RL on RL.MAINFORMULAKEY = F.ID 
  left join EVT_OBJECTEVENT oe on oe.FUNCTIONKEY = F.ID 
where 
  (F.SCRIPT like '%" & gdcBaseManager.GetRuidStringByID(id) & "%') 
  or (F.SCRIPT like '%" & CStr(id) & "%') 
order by 
  3, 5, 4   
````

**Comment by gsbelarus** [comment]
> Зачем, счета, входящие в некоторые ПИ, пересохранять?

Потому что они могут быть сохранены в файлах ПИ со старым названием. 

> Что же будет, когда exe выполнит modify плана счетов ? Будет множество вопросов и проблем: "Где 92-е счета ?"

Нигде, ни у какого клиента, ничего не нарушится. Все проводки сохранятся, все ТХО, ТП продолжат работать. Максимум -- добавится подчеркивание в название счета. Это в любой момент потом можно будет решить редактированием названия в плане счетов.

Еще раз повторю -- если хоть одна самая дохлая проводка завалялась в базе данных по счету, или остаток есть, или автопроводка, или он задействован в скрипт-функции, или еще где -- он удаляться не будет.

> По поводу SQL-запроса не согласен

Запрос приведен для примера. В реализации, естественно, будет использоваться более полный запрос.

> Да и сам план счетов с его разделами с ID < 147000000

Это не принципиально в данном случае. Будут ли там ИД системные (меньше 147 000 000) или пользовательские. Все равно мы идем к базе данных с готовой конфигурацией. Т.е. документы + план счетов + настроенные проводки по нему. А настроить проводки можно только в том случае, если у всех клиентов будет один план счетов, где, скажем счет 01 имеет одинаковый, известный РУИД. Будет ли этот РУИД 300222_17 или 147555999_434343434 -- абсолютно никакой разницы не имеет.

> В приоритете данной задачи новые клиенты, а не старые

И те, и те в приоритете. Новые должны работать на типовом. Старые -- продолжить с тем, что у них уже есть. НО! Если старому понадобится новая наша подсистема, то мы должны иметь возможность поставить типовое решение, чтобы оно "совместилось" с его планом счетов с минимальными вмешательствами.

> Когда заходит речь о совершенно новом плане счетов

Речь идет об актуализации существующего плана счетов, приведение его в соответствие с законодательством, сегодняшними рекомендациями минфина и т.п. При этом стараемся не порушить то, что уже работает у клиентов. Счета, которые были в скриптах -- там и останутся. В ПИ их тоже можно включать. Новые счета делаем уже через ПИ, так как это проще -- не надо каждый раз модифай базы писать.

Вообще, тут просматривается другая проблема. Как, при загрузке счета, не порушить существующие аналитические признаки. Ее решим отдельно, на уровне платформы.

> Нельзя ли было в течение этого срока среагировать и начать работы постепенные работы по обновлению плана счетов?

Последнюю пятилетку мы шли в сторону индивидуальных настроек под конкретного клиента. Поэтому данная задача не была первоочередной. Сейчас пытаемся получить типовое тиражное решение и приоритет данной задачи стал найвысшим. Все как в жизни. Есть неограниченные потребности и реальные возможности. Задача совместить их.

**Comment by NikolayUkleyko** [comment]
>Последнюю пятилетку мы шли в сторону индивидуальных настроек под конкретного клиента. Поэтому данная задача не была первоочередной.

##### Я не считаю это причиной, чтобы не привести в план счетов к актуальному состоянию.

  Я не понимаю одного. Если, в эталон не были включены типовые проводки и прочее, то чего в эталон был включен план счетов ?
  
  Написано много всего, а конкретики нет. Я так, понял, что необходимо только поправить счета, поменявших назначение ? Согласно файла https://docs.google.com/spreadsheets/d/1CPEuIa38lKa-0RTH7lBMLWd9vMpGtj0AhxbxoOnZU4o/edit#gid=1503794625

**Comment by gsbelarus** [comment]
> Что надо сделать:
>
> 1.    Апгрейдить БД (апгрейд еще не готов! я напишу сюда когда сделаю) или вручную переименовать старый счет в "_10.08".
>2.    Создать новый счет, с новым описанием и новым РУИД-ом. Включить его в ПИ плана счетов.
> 3.   Пройтись по всем ТП и заменить в блоках проводок старый счет на новый.
> 4.    Пересохранить все ПИ с измененными ТП.

**Comment by gsbelarus** [comment]
Первая часть сделана. Скрипты приведены в соответствие с файлом. Обратите внимание, там где в файле меняются номера счетов (я выделил темно зеленым фоном) я просто удаляю счета из плана счетов, из скриптов. Новые счета (а смена номера счета, как мы договорились выше, это удаление старого счета и создание совершенно нового) должны быть созданы через ПИ.

Проверил загрузку Комплексной автоматизации на новый эталон -- выполняется нормально.

Теперь дело за модифаем для существующих баз.

**Comment by NikolayUkleyko** [comment]
Все это хорошо.
  Доделал план счетов и закинул в ПИ (v.2).
  Теперь пробуйте выполнять манипуляции.

**Comment by NikolayUkleyko** [comment]
По-хорошему необходимо вообще отвязать план счетов от скриптов (постепенно). Так как, при малейших изменениях, не поправив скрипты, не будет грузится комплексная автоматизация.

**Comment by NikolayUkleyko** [comment]
Данный вопрос решен.
  Если, ни у кого нет вопросов, закрывайте тему.
