### ISSUE TITLE
Etalon business. Бухгалтерия. Исправить/создать/скрыть отчеты

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#53]
Исследователь > Бухгалтерия.
1. Предлагаю скрыть отчеты по документу "План счетов" > Отчеты "План счетов", "План счетов (полный)". Зачем они нужны, если есть единая форма отчета ? 
2. Пожалуйста, в отчете "План счетов (подробный)" предусмотрите отображение значения аналитики "Аналитика для развернутого сальдо".

**Comment by MBurakina** [comment]
Обновляй ПИ "Общие данные бухгалтерии"

**Comment by NikolayUkleyko** [comment]
Проверено.
  Работает корректно.
  Спасибо !

:+1: :blush:
