### ISSUE TITLE
Изменил шаблон и не запускается отчет

### ISSUE THREAD

**Issue by dadantbp** [GoldenSoftwareLtd/gedemin-apps#58]
В шаблоне добавил строковое поле, сохранил, после этого отчет не запускается, ошибка GroupHeader1: Ошибка в выражении REPORT."DOCID": Identifier exppected, может что-то надо еще изменить что бы отчет запустился

**Comment by gsbelarus** [comment]
а поле такое есть в датасете REPORT?

**Comment by dadantbp** [comment]
это не поле БД, я добавил обычный текст

**Comment by alexandra-gsoftware** [comment]
REPORT - это набор данных, который формируется в функции отчета. Следовательно, и поле DOCID Вам нужно добавить сначала в этой функции.

**Comment by dadantbp** [comment]
Дело в том, что отчет у меня прекрасно работал, я просто добавил текстовое поле со значением "Согласовано" и сохранил шаблон, больше не каких манипуляций с кодом или с полями БД я не делал. Можно подробнее что и где нужно еще изменять. Спасибо.

**Comment by dadantbp** [comment]
Функция отчета я не изменял, там все прописано, я изменил только шаблон

**Comment by gsbelarus** [comment]
1. В функции отчета, где готовятся данные, сначала надо добавить поле. Если данные извлекаются SQL запросом, то в его часть SELECT. Если данные формируются "вручную" и помещаются в т.н. клиент-датасет, в оперативной памяти компьютера, то добавить поле с помощью вызова AddField и соответственно заполнить его.
2. Выполнить функцию, убедиться что она работает без ошибок и нужная вам колонка появилась в результируещем наборе данных.
3. После этого идти в редактирование шаблона и добавлять поле на нужный бэнд, чтобы оно появилось при построении отчета.

**Comment by dadantbp** [comment]
Может после пересохранения шаблона слетела привязка к документу и не может получить DOCID документа, по которому запускается отчет?

**Comment by MAliaksandr** [comment]
Скорее всего слетел dataset

**Comment by dadantbp** [comment]
Как его можно восстановить?

**Comment by gsbelarus** [comment]
Да ничего не слетело. GroupHeader1 точно привязан к датасету? Раньше был привязан? Где вообще прописываются это поле? Квадратные скобки используются?

Ничего не ясно из описания. Дайте тогда сюда скриншоты:

1. Функции
2. Результата ее выполнения
3. Шаблона (в момент редактирования)

Чтобы что-то сказать точно, а не гадать.

**Comment by dadantbp** [comment]
Датасет не слетел, как выше писали, набор данных берется из функции, к датасету ничего не привязано, раньше так же не было привязано, квадратные скобки как и во всех других отчетах не используются, поле прописывается в свойстве Condition объекта GroupHeader1 (что-то не нашел где этот объект привязывается к набору данных)

Код скрипта:
Function rp_Main243392110_1369903745253096208_1428921744(OwnerForm, BuhKey)
  BaseQueryList.Clear
  doc = OwnerForm.SelectedKey
  id = "(" + join(doc(0), ",") + ")"
'  id = "(280109558)"
  if id = "()" then
    call Exception.Raise("Exception", "Ïóñòîé íàáîð äàííûõ")
  end if
  
  set Contact1 = BaseQueryList.Query(BaseQueryList.Add("Buh", 0))
  Contact1.SQL = "select " & _
    "  con.name, p.rank " & _
    "from " & _
    "  gd_contact con " & _
    "  left join gd_people p on con.id = p.contactkey " & _
    "where " & _
    "  id = :id "
  Contact1.ParamByName("id").AsInteger = BuhKey(0)
  Contact1.Open

  
   set MainFirm = BaseQueryList.Query(BaseQueryList.Add("MainFirm", 0))
   MainFirm.SQL = "select " & _
     "  cf.*, " & _
     "  dir.name as DirName, " & _
     "  p.rank as DirRank " & _
     "from " & _
     "  gd_v_company cf " & _
     "  left join gd_company comp on comp.contactkey = cf.id " & _
     "  left join gd_contact dir on dir.id = comp.directorkey " & _
     "  left join gd_people p on p.contactkey = dir.id " & _
     "where " & _
     "  cf.id =  "  + CStr(System.Company.ID)
   MainFirm.Open

   set qReport = BaseQueryList.Query(BaseQueryList.Add("Report", 0))
   qReport.SQL = _
     "select " & _
     "  doc.parent as DocID, " & _
     "  doc.id as DocLineID, " & _
     "  ToCon.name as ToContactName, " & _
     "  FromCon.name as FromContactName, " & _
     "  doc.documentdate, " & _
     "  doc.number, " & _
     "  a.alias as AccAlias, " & _
     "  g.name as GoodName, " & _
     "  g.alias as GoodAlias, " & _
     "  coalesce(g.usr$mn_measure, 1.0000) as GoodMeasure, " & _
     "  v.name as ValueName, " & _
     "  m.debit as Quantity, " & _
     "  coalesce(c.usr$inv_costprovider, c.usr$inv_costbuyncu) as costprovider, " & _
     "  c.USR$INV_ISFIXEDCOST as ISFIXEDCOST, " & _
     "  c.usr$inv_costbuyncu as costbuy, " & _
     "  c.usr$inv_costtradencu as costtrade, " & _
     "  c.usr$inv_costtrwithnds as costtrwithnds, " & _
     "  c.usr$inv_extra as extra, " & _
     "  c.usr$inv_extracost as extracost, " & _
     "  c.usr$inv_extrands as extrands, " & _
     "  c.usr$inv_extraservicecost as extraservicecost, " & _
     "  c.usr$inv_selcostncu as selcost, " & _
     "  c.usr$inv_sellnds as sellnds, " & _
     "  c.usr$inv_taxservice as taxservice " & _
     "from " & _
     "  inv_movement m " & _
     "  join gd_document doc on doc.id = m.documentkey " & _
     "  left join inv_movement m1 on m1.movementkey = m.movementkey and m1.id != m.id " & _
     "  left join gd_contact ToCon on ToCon.id = m.contactkey " & _
     "  left join gd_contact FromCon on FromCon.id = m1.contactkey " & _
     "  left join inv_card c on c.id = m.cardkey  " & _
     "  left join gd_good g on g.id = m.goodkey " & _
     "  left join gd_value v on v.id = g.valuekey " & _
     "  left join ac_account a on a.id = c.usr$inv_accountkey " & _
     "where " & _
     "  m.debit > 0 " & _
     "  and doc.parent in " & id & _
     " order by " & _
     "  doc.parent, " & _
     "  a.alias, " & _
     "  doc.id "
   qReport.Open
  
  set rp_Main243392110_1369903745253096208_1428921744 = BaseQueryList
end function

![image](https://cloud.githubusercontent.com/assets/14332006/9938951/59fca3c4-5d70-11e5-8bc4-e286a838bb40.png)

**Comment by alexandra-gsoftware** [comment]
Посмотрите, что в Меню фаст репорта -> Отчет -> Данные?

**Comment by dadantbp** [comment]
ничего нет, пусто, в других отчетах, которые работают, в редакторе шаблона в Отчет -> Данные тоже пусто

**Comment by MAliaksandr** [comment]
А в мастердата выбрать нужный набор данных

**Comment by alexandra-gsoftware** [comment]
Вот в этом окне ничего нет?

![reportdata](https://cloud.githubusercontent.com/assets/11487200/9940327/ce433bd8-5d77-11e5-9a30-ed3e0dd7c106.PNG)

**Comment by dadantbp** [comment]
В том то и дело, почемуто в другом отчете, если выбрать данный шаблон то данные есть, а в этом проблемном отчете на любых шаблонах данных нет, пусто, почему такое произошло?

**Comment by alexandra-gsoftware** [comment]
попробуйте запустить только функцию отчета (из редактора скрипт-объектов кнопка Запуск скрипта), а потом зайти в шаблон и посмотреть опять Данные отчета

**Comment by dadantbp** [comment]
убрал из параметров функции OwnerForm, так как вызываю не из документа, прогнал функцию, зашел в редактор шаблона и "данные" были на месте, пересохранил шаблон, привел функцию к оригинальному виду и совершилось, отчет запустился, всем большое спасибо за помощь!

**Comment by alexandra-gsoftware** [comment]
ура)
