### ISSUE TITLE
При загрузке ПИ комплексной автоматизации

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/gedemin-apps#6]
1)

21:00:45  Добавляется объект: 147015029_119619099, USR$WG_HOURTYPE
[Предупреждение] 21:00:45  Отсутствует в базе: USR$FORPU3

2)

21:00:49  Добавляется объект: Все организации, 151821044_630959, gd_contact
[Предупреждение] 21:00:49  Отсутствует в базе: USR$MN_USEPORTION

3)

21:03:38  Изменяется объект: 01.01, 300101_17, ac_account
[Предупреждение] 21:03:38  Отсутствует в файле: "AC_ACCOUNT"."USR$INV_CUSTPERMITKEY"

4)

21:10:26  Добавляется объект: Золото, 147112714_1439110857, GD_GOOD
[Предупреждение] 21:10:26  Отсутствует в базе: USR$CMPD_FIRSTGROUPKEY

**Comment by alexandra-gsoftware** [comment]
вроде все исправила, проверьте
