### ISSUE TITLE
Бухгалтерия. Отчеты бухгалтерии. Справочник показателей. Доработать макросы добавления объектов в ПИ

### ISSUE THREAD

**Issue by NikolayUkleyko** [GoldenSoftwareLtd/gedemin-apps#61]
Исследователь > Бухгалтерия > Отчеты бухгалтерии > Справочник показателей.
  При попытке добавления отдельной ветки с входящими в нее показателями в ПИ при помощи макроса "Добавить показатели в ПИ" программа отображает окно с ошибкой. 
![1](https://cloud.githubusercontent.com/assets/11497453/10206693/d5d01994-67d0-11e5-8827-eca0d1f069d7.png)
Это связано с тем, что часть показателей уже входит в определенные ПИ.
  Необходимо сделать следующее:
1. Предусмотреть корректную работу макросов по **тихому** добавлению объектов в ПИ. Даже, если часть объектов уже входит в некие ПИ, а часть - нет.
2. Предусмотреть возможность добавления самой верхней ветке, на которой указан курсор для последующего добавления объектов в ПИ.
3. Предусмотреть добавление объектов в ПИ в **правильной последовательности**. При формировании отчета "Неверные зависимости" (форма "Пространства имен") не должно быть некорректных данных.

  Все вышеизложенное имеет силу как к показателям, так и к составляющим показателя. То есть,  необходимо доработать макросы "Добавить показатели в ПИ" и "Добавить значения показателей в ПИ".

**Comment by MBurakina** [comment]
Нет, эта ошибка не связана с добавлением в ПИ объекта, входящего в иные ПИ. Давай просто свою последовательность действий.

**Comment by MBurakina** [comment]
ПИ "Показатели".

**Comment by NikolayUkleyko** [comment]
Огромное спасибо, Марина !
  Все получилось.
  Закрываем тему.
