### ISSUE TITLE
Добаработать отчет Неверные зависимости

### ISSUE THREAD

**Issue by alexandra-gsoftware** [GoldenSoftwareLtd/gedemin-apps#8]
1 В отчете отображаются crosstablekey у ссылок на множество и fieldsourcekey для вычисляемых полей. Нужно их не показывать

**Comment by alexandra-gsoftware** [comment]
2. Доделать отчет Объекты данного ПИ, которые больше никуда не входят, чтобы в нем, как в остальных, можно было открывать объекты на редактирование

**Comment by MBurakina** [comment]
Закрываем?

**Comment by alexandra-gsoftware** [comment]
ага.
